### ISSUE TITLE
Emulator runs at ~70% of actual speed

### ISSUE THREAD

**Issue by Bombe** [atari800/atari800#1]
Hi,

I compiled atari800 (commit 8e76305) on OS X (macOS Sierra, 10.12.6) without any problems. However, even when nothing is loaded (e.g. only BASIC), the emulator shows that a speed of about 70% (using the -showspeed option) of the actual speed is reached. This number oscillates a bit but never reaches 100%. At the same time the CPU usage is only about 15%.

This also means that everything is running slow, sound is choppy, and all that jazz.

Did I miss something? Is there anything I can disable, either at compile time or at run time, to make it run at 100%?

Greetings,
    Bombe

**Comment by knik0** [comment]
Hello, 
There are rumors atari800 sound on OS X Sierra is broken. You could run it with -nosound option and see what happens.

**Comment by ChoccyHobNob** [comment]
I run atari800 on macOS sierra and the sound is fine.

**Comment by joysfera** [comment]
@ChoccyHobNob and what about the speed? Is it running at 100 %?

**Comment by ChoccyHobNob** [comment]
I just ran starraiders.car. I get 99-100%, windowed and fullscreen. The same when running -nosound
![atari001](https://user-images.githubusercontent.com/12753/29283864-0cfa30f2-80ee-11e7-9e00-22d10a6413d5.png)

**Comment by ChoccyHobNob** [comment]
Same is true when running nothing...
![atari002](https://user-images.githubusercontent.com/12753/29283972-943f8792-80ee-11e7-9852-644d93013147.png)
![atari003](https://user-images.githubusercontent.com/12753/29283974-9722feda-80ee-11e7-9bc8-bad0a59082e6.png)

**Comment by ChoccyHobNob** [comment]
Maybe the sound 'rumour' is from someone running Atari800MacX?

**Comment by ChoccyHobNob** [comment]
Just to be sure I just cloned the latest source and built again. Same results, works fine.

**Comment by joysfera** [comment]
@ChoccyHobNob could you please make your binary available to others? Can you pack it somehow so that other Mac users could unpack it and run it?
Another question is if there is someone supporting the Atari800MacX actively. It's been a native (Cocoa?) port, IIRC. Did you just compile the SDL port for OS X?

**Comment by ChoccyHobNob** [comment]
This is the compiled binary, stick it somewhere in the path and run from terminal or ./atari800 (or double click) from the current dir.

http://choccyhobnob.com/?d=1915

I haven't seen an update to Atari800MacX for years (2011) and honestly, the UI looks like it dates back that far as well, but if you google "atari emulator mac" you get hits to that everywhere.

**Comment by ChoccyHobNob** [comment]
I've sent a message to the author of Atari800MacX asking if his emulator is still in development and whether he knows of any problem with the sound on macOS Sierra

**Comment by joysfera** [comment]
@Bombe could you tell us how Steve's binary work for you? If it runs at 100% speed, any idea why your build is different?

**Comment by Bombe** [comment]
After updating libpng @ChoccyHobNob’s binary runs and shows around 100% speed. However, for some reason my self-compiled binary now also runs at ~100%. They are both kind of flaky, i.e. playback (or emulation) does not sound stable… and atari800 seems to completely take over macOS’s audio system, as in Spotify stops when atari800 starts and automatically resumes when it ends.

**Comment by ChoccyHobNob** [comment]
@Bombe It feels pretty solid here, with the right combination of options, atari800 will run _almost_ everything I throw at it.

There is a solid 'thunk' sound when a8 starts and inits audio. I tried to play some Floyd in iTunes while Adam Gilmore's awesome Zybex theme was running and it overlays correctly, horribly ruining both bits of music as expected. 

If I start atari800 without a game running, I can happily type away in BASIC or doodle in Atariartist and hear the keyclicks mixed in with the music I'm playing in iTunes. Sorry I can't test with Spotify, I don't have it. 

This is one of those areas where macOS lags behind windows, there is no system audio mixer. You can get 3rd party software like [Sound Control](https://staticz.com/soundcontrol/) to fix that issue but by default you have to rely on apps playing nicely together or implementing their own volume controls. Atari800 is behaving exactly as I would expect it to given the system it's running on and the age of the SDL that it's using. 

@joysfera any idea when/if SDL2 is on the roadmap at all? Hardware OpenGLES2 on SBC's, Proper Shaders and Proper Joypad configuration are pretty tempting? 😉

**Comment by Bombe** [comment]
Okay, I take back everything I said about atari800 hogging the audio, because PEBKAC, it was actually Alexa stopping its Spotify client as soon as it got a signal from atari800 over Bluetooth. When using internal audio it’s all mixed together, just as expected. I still need to run some tests with actual demos/songs, though. :)

**Comment by joysfera** [comment]
Sounds like this issue can be closed?
SDL2 is something I'd like to talk about in the mailing list. I have some mixed feelings about that.

**Comment by Bombe** [comment]
Yes, I can’t reproduce the original issue anymore. Thanks for the help, everybody!
