### ISSUE TITLE
"Bounty Bob Strikes Back" Cart version doesn't run 

### ISSUE THREAD

**Issue by ChoccyHobNob** [atari800/atari800#10]
[This file at atarimania](http://www.atarimania.com/game-atari-400-800-xl-xe-bounty-bob-strikes-back_6014.html), doesn't run. The static background appears but the birds don't fly on. Pressing start tries to start the game but it doesn't ever display the first level

It runs OK in Altirra

**Comment by ChoccyHobNob** [comment]
OK I thought I was wrong but I'm not. 

If I run a8 with no cfg file and just pass the cart, it runs ok
If I run with a cfg file and no cart it starts up, picking the cart from the cart menu will run it ok
running a8 with a cfg file and passing the cart on the command line doesn't work

**Comment by joysfera** [comment]
This is getting interesting now...

**Comment by ChoccyHobNob** [comment]
I've tried every option I can think of in the cfg file, it makes no difference what system, os, basic, memory, harddrive, printer, rtc, region etc etc  I try.

**Comment by ChoccyHobNob** [comment]
Every other .car file I've tried works fine, even the xegs and 5200 ones

**Comment by joysfera** [comment]
Works for me.
Steps:
1) download, unzip
2) atari800 -cart /path/to/file

**Comment by ChoccyHobNob** [comment]
Still doesn't work here, downloaded the cart rom (big five version) again from atarimania just to be sure. 

renamed bbob.rom for ease

atari800 -cart bbob.rom

![screen shot 2018-04-21 at 16 30 54](https://user-images.githubusercontent.com/12753/39088969-d107d064-4581-11e8-9509-b752234d4dd7.jpg)

birds never appear

convert rom to .car and try again, still doesn't work

**Comment by ChoccyHobNob** [comment]
Found it! 

It doesn't like stereo pokey being enabled. 

That's the first ROM I've found that doesn't just ignore the extra pokey being enabled. 

Thanks @joysfera

**Comment by ChoccyHobNob** [comment]
Reopening this LOL sorry! 

The initial inconsistency still exists, if I start atari800 with stereo enabled and no ROM inserted, then add the bbob rom, it works (the lower pitched 'thunk' noise when the birds show up comes out of the left channel, the high pitched 'tink' noise when the birds place the letters is more muffled and comes out of the right channel, but the game start), if I "atari800 -cart bbob.rom" it doesn't. Turn off stereo and it works both ways.

**Comment by mikrosk** [comment]
@ChoccyHobNob can you verify how this is behaving on real hardware? Enabling stereo just changes how the POKEY registers behave, it should be the same as on real hardware. Does it work in Altirra in this setting?

**Comment by ChoccyHobNob** [comment]
Here’s Avery discussing why it happens. 
291337-u-switch <https://atariage.com/forums/topic/291337-u-switch/?do=findComment&comment=4284257>

I only have a 1088XEL with stereo POKEY’s, I’ll try running a few versions of BBSB on it today.

**Comment by joysfera** [comment]
The description sounds like the bug is in software (that basically uses wrong registers). I'd close the issue.

**Comment by ChoccyHobNob** [comment]
OK

**Comment by mikrosk** [comment]
Agreed, definitely not something Atari800 should fix. But it's great it helped to discover the problem. :)
