### ISSUE TITLE
How To Install on macOS - Blank Window

### ISSUE THREAD

**Issue by dmmx** [atari800/atari800#104]
I am trying to install and run atari800 on my mac. I tried installing via HomeBrew:
```shell
$ brew install atari800
```
The install seemed to go smoothly, but when I try to run the program, a blank window pops up. In Terminal only a few lines of output appear:
```
Using Atari800 config file: /Users/dan/.atari800.cfg
Created by Atari 800 Emulator, Version 4.2.0

Requested resolution 336x240 is not available, using 640x480 instead.
Video Mode: 336x240x32 windowed without vsync
```

Are there specific configuration values I need to add to the .atari800.cfg file? Do I need to compile/install the program manually? If so what configuration values/flags should I use?

**Comment by mikrosk** [comment]
Hmm, not sure who has a Mac from the developer team. This would require attaching debugger and/or adding some debug outputs.

**Comment by TheRobotFactory** [comment]
I get the same issue if I remove the default .cfg file, one isn’t created if it doesn’t already exist and the emulator hangs if it can’t open a cfg

I didn’t try it on any other platform

**Comment by TheRobotFactory** [comment]
Further to that, a default config is created when I run without one but it still doesn’t allow the emulator to start. 

Didn’t we have this problem when we first switched to AltirraOS? I don’t remember what was done to get around the problem.

**Comment by mikrosk** [comment]
Wait so you are saying @TheRobotFactory that if you let your old config file in place it does start?

**Comment by TheRobotFactory** [comment]
Yes 
It has nothing to do with AltirraOS.

If you just change VIDEO_ACCEL=0 to VIDEO_ACCEL=1 in the default empty CFG file it then starts up OK

**Comment by dmmx** [comment]
Thanks All, setting VIDEO_ACCEL=1 worked. 

Is this the best forum to use if I have other questions about the emulator?

**Comment by dmsc** [comment]
Thanks @dmmx
You should reopen this issue, it needs to be properly solved!

**Comment by dmmx** [comment]
Reopened per @dmsc

**Comment by krischik** [comment]
Without VIDEO_ACCEL everything looks as expected but is almost unusably slow.

<img width="1278" alt="Screenshot at Sep 22 20-41-32" src="https://user-images.githubusercontent.com/685853/93923946-5e361f80-fd14-11ea-96a6-d7596bc86473.png">

 With VIDEO_ACCEL everything is as fast as expected but the window isn't filled:

<img width="1133" alt="Screenshot at Sep 22 20-42-24" src="https://user-images.githubusercontent.com/685853/93924038-7c9c1b00-fd14-11ea-82df-0b1be5a84230.png">

**Comment by krischik** [comment]
I noted the [Atari800MacX](http://www.atarimac.com/atari800macx.php) is displaying correctly. In addition to having a ton of other need functions.

And since it uses the atari800 as base I wonder what the difference is.

**Comment by pedgarcia** [comment]
Does Atar800 uses SDL1 or SDL2? I know that Atari800MacX was recently ported to a newer version of SDL2 and also replaced opengl to metal. Maybe that's why?

**Comment by krischik** [comment]
@pedgarcia Yes, indeed:

> New Features/Bug Fixes (in version 5.1.0):
> …
> Updated application to use Apple's Metal API instead of OpenGL. MacOS has depricated OpenGL, and this should help to future proof the program.

> New Features/Bug Fixes (in version 5.0.0):
> …
> Changed from using underlying SDL Library 1.2 to SDL Library 2.0. This allows operation on Mac OSX Sierra, High Sierra, and Mojave. Note, no testing has been done on Sierra and High Sierra.

Yes, I expect that's the reason as well. Too bad those patches where not send upstream.

**Comment by emabolo** [comment]
I was using a version of atari800 compiled from src code on my mac with Catalina and it was working properly with VIDEO_ACCEL=0. Now with Big Sur, the emulator window is white. I tried to compile the 4.2 and it's the same. If I change VIDEO_ACCEL to 1, it works, but I can see the emulator screen in the left bottom part of the window, as shown in the screenshot sent by krischik. 
Do you have any news about this issue?

**Comment by krischik** [comment]
I don't. A change to  SDL Library 2.0 and Metal API is needed. Since @atarimacosx did it already it should not be too much work.

**Comment by emabolo** [comment]
Ok, I hope someone will do it soon.
Anyway, I wonder with VIDEO_ACCEL you can see the screen (even if the app is not useful), while in my case I only see a white screen. Weird

**Comment by krischik** [comment]
It seems the problem has been fixed in SDL itself. Display not works as expected both for the MacPorts and Brew distribution. However now we have a new problem: #177 _„CTRL Key not working on macOS (MacPorts and Brew)“_ .
