### ISSUE TITLE
Real joystick doesn't work in Atari SDL port

### ISSUE THREAD

**Issue by mikrosk** [atari800/atari800#105]
Neither XBIOS nor IKBD. Possibly bug in Atari SDL port.

**Comment by joysfera** [comment]
it's not obvious from #81 but has @jasonculligan the issue on an Atari computer? What Atari has USB, anyway?

Edward S. Baiz Jr. just reported me directly via email that joysticks connected to TT keyboard hooked to Firebee don't work.

**Comment by mikrosk** [comment]
Verified - SDL port ignores joystick input entirely and Falcon port works but the trigger is somehow stuck, one has to press mouse button to unstuck it.

**Comment by pcrow** [comment]
I was having trouble with my Stelladapter and an Atari CX40+ joystick with 5.0.0 on Linux, but it works with 5.2.0.
Has this been fixed?

**Comment by mikrosk** [comment]
That would be great but I think this one is related to real Atari Falcon DSUB9 joysticks. If generic joystick support didn't work in 5.0.0, that's quite scary but good that it has been fixed in the meantime. :)

If I find time, I'll try to give reproduce this bug, too but as mentioned, I think this is unrelated.

**Comment by joysfera** [comment]
@pcrow what is Stelladapter? This issue is about Atari Falcon/TT port of Atari800, completely unrelated to any issue you might have had.

@mikrosk please better put the word "Falcon" in the issue title next time as "Atari SDL" is confusing for most Atari800 users - I believe almost everybody don't realize Atari800 runs on other Atari computers :-)

**Comment by pcrow** [comment]
Stelladapter is a USB adapter for using real Atari joysticks.  I know it worked some time in the past, but recently I had having trouble.  5.0.0 mentioned something about detecting joystick 0, but 5.2.0 reports "Joystick 0 mapped to emulated joystick 0" so I think I was getting a mapping issue.  This was on Linux with SDL, hence the confusion with SDL in the issue report.  Anyway, I'm not clear on whether my previous issue was something I was doing wrong or a bug, but either way it's working now, so no need to open a new issue.

BTW: I did see the "TT" and thought this might be an ST issue (and I do know this runs on the ST), but from the title I assumed it was a general SDL issue.
