### ISSUE TITLE
Support for Atari 5200 bank switchable carts. 

### ISSUE THREAD

**Issue by TheRobotFactory** [atari800/atari800#106]
Back in 2005 a bank switching cartridge was created for the Atari 5200 allowing up to 512KB. There has been some uptake in the Homebrew community but currently Real hardware or Altirra are the only way to run these cart images.

Details of the board are here https://atariage.com/forums/topic/69649-5200-game-announcement-now-shipping/?do=findComment&comment=856153

Example carts are attached. 

[Examples.zip](https://github.com/atari800/atari800/files/4660654/Examples.zip)

**Comment by joysfera** [comment]
Should be implemented now thanks to @asiekierka
