### ISSUE TITLE
USB Joystick support

### ISSUE THREAD

**Issue by AmitZohar44** [atari800/atari800#107]
Hi,
I'm using this great emulator on Windows for many years with a true joystick connected to a parallel port. It appears as "LPT1 Printer Port" in the device manager: 
![joystick lpt1](https://user-images.githubusercontent.com/66167494/83328472-ea1acc00-a28b-11ea-81af-96be2cca486b.PNG)
The joystick works with the PPJoy driver.

In my laptop I don't have a parallel connector so I'm trying to use a USB to parallel converter. However, it doesn't appear as LPT1 anymore but as "USB printing". Thus, the PPJoy driver doesn't recognize the Joystick (when I click "test" and move the stick nothing happens). I can think of 2 options:

1. Configure the USB converter as LPT1, but I can't find how to do it (tried to read some stuff from Microsoft but in vain)
2. Connect the Joystick to Arduino (without PPJoy) and send the Joystick actions to a PC application.
![atariJoy](https://user-images.githubusercontent.com/66167494/83328488-fe5ec900-a28b-11ea-886d-f7487d01ff3e.png)
In this option, what's the best way to send the Joystick actions from MyApp to the Emulator? Emulate keystrokes or some other way? I'm afraid that using keystrokes will cause lags.
If I implement it I'll gladly share the Arduino and PC applications' code.
Does someone has an idea? Thanks in advance, Amit

**Comment by joysfera** [comment]
Consider this proven solution:

https://joy.sophics.cz/dual-joystick-usb-adapter/

No need to modify Atari800 in any way.

**Comment by joysfera** [comment]
If you want to build it yourself using your Arduino then simply emulate an USB joystick connected to your PC. Then you'll need no additional app and Atari800 will work out of the box.
