### ISSUE TITLE
libatari800 Status

### ISSUE THREAD

**Issue by carmiker** [atari800/atari800#112]
Hello there.

I am working on a new port of Atari800 and was hoping to use libatari800. However, I am seeing in the documentation that sound is not done yet, despite there being some sound related code in libatari800. I'm also noticing that input is not very well documented and some pieces seem not to be hooked up there from what I can tell -- specifically console keys (correction - it is defined elsewhere).

I am curious about the status of this build. It looks like a few years have passed since any significant work was done on it. Is it considered complete for the purposes it was built for? Are there plans to utilize this further? It is a great concept, and it could be used by many of the current platform specific ports to simplify things.

Thank you.

**Comment by mikrosk** [comment]
I guess @robmcmullen could answer some of your questions regarding libatari800.

So far, he has used it for his debugger, I'm not sure how plausible is to use it for a new port. Porting Atari800 to a new architecture is rather easy, so maybe you would be fine with adding it as the others.

**Comment by carmiker** [comment]
Thank you for your response, @mikrosk. I ended up writing my port using libatari800 as a guideline. In the process I realized how I could have stretched libatari800's capabilities to get the job done. There are only a few small pieces missing from my perspective:
1. There is no clear way to access the audio buffer, one would need to define 'extern UBYTE *LIBATARI800_Sound_array;' somewhere and also know how many samples were written. It appears the audio is actually being written but the hooks to make it easy to access do not currently exist.
2. The pixel format is unclear. When I was working with libatari800 initially, I ended up including "colours.h" and using some of the functions declared there to decode the pixel data and rewrite it into a new buffer. Perhaps this could be done differently, but I was unable to discern what the original pixel format is.
3. Input is not documented, and looks to be somewhat complex to deal with, especially if you are like me, and coming to this system with little background knowledge.

I think overall, more documentation would go a long way to making libatari800 viable for new ports.

**Comment by robmcmullen** [comment]
@carmiker libatari800 can definitely use more polish. For your specific questions:

1. I do not yet understand how audio works, and I was assuming that it would generate a fixed number of samples per video frame. But I haven't been able to get the audio buffer to fill at all.
2. The pixel format in the video buffer is one byte per pixel in Atari color format, so high nybble is color and low nybble is luminance.
3. I thought I had written up something about the input, but apparently not. The input structure is designed to be pretty similar to the inputs needed by the normal code, so input->keycode is simply a keycode from akey.h, or you can use input->keychar to use ASCII values. I will do some documentation. You can look at https://github.com/atari800/atari800/blob/master/src/libatari800/libatari800_test.c for a super simple example where I put an "a" value into the keyboard buffer at every frame.

**Comment by asiekierka** [comment]
Out of curiosity, which platform are you looking at that would prefer porting via libatari800 and not atari800 as a whole?

**Comment by carmiker** [comment]
@robmcmullen thank you for your response.

Audio can be tricky. The way I ended up doing audio was to use the Sound_Callback which can enabled in config.h, since it allows me to grab as many samples as I want at a time instead of having yet another ring buffer to manage. There are still some issues to work out in my port, but it is most of the way to perfection as far as audio is concerned now.

@asiekierka I am in the process of building an education-oriented, cross-platform multiple emulator system.

**Comment by mikrosk** [comment]
For the future, feel free to ask on the mailing list to discuss this kind of questions. :)
