### ISSUE TITLE
[Feature Request] Support for analog joystick

### ISSUE THREAD

**Issue by Shoegzer** [atari800/atari800#124]
The Atari 5200 CX-52L joystick is [analog](http://www.atarimuseum.com/videogames/consoles/5200/5200joy.html), however this core only permits directionals via the digital d-pad.  This makes playing games such as Centipede, Missile Command and Kaboom! difficult to play at best, or unplayable at worst.  

@kr0tki If there's any chance you could look into this whenever you may have some time, I'm happy to help out with testing etc.

**Comment by mikrosk** [comment]
Will be fixed by #224.
