### ISSUE TITLE
Check and possibly fix compiler warnings in Fedora

### ISSUE THREAD

**Issue by joysfera** [atari800/atari800#128]
Ján Ondrej created fresh Atari800 package and pushed it into Fedora/CentOS. There are build logs that show some suspicious compiler warnings we should better check and try resolving eventually:

https://kojipkgs.fedoraproject.org//packages/atari800/4.2.0/2.fc35/data/logs/x86_64/build.log
https://kojipkgs.fedoraproject.org//packages/atari800/4.2.0/2.fc35/data/logs/i686/build.log
https://kojipkgs.fedoraproject.org//packages/atari800/4.2.0/2.fc35/data/logs/ppc64le/build.log
https://kojipkgs.fedoraproject.org//packages/atari800/4.2.0/2.fc35/data/logs/s390x/build.log

**Comment by dmsc** [comment]
Hi!

> Ján Ondrej created fresh Atari800 package and pushed it into Fedora/CentOS. There are build logs that show some suspicious compiler warnings we should better check and try resolving eventually:
> 
> https://kojipkgs.fedoraproject.org//packages/atari800/4.2.0/2.fc35/data/logs/x86_64/build.log

Just took a look at this:

```
In file included from /usr/include/string.h:519,
                 from devices.c:32:
In function 'memcpy',
    inlined from 'Devices_RestoreHandler' at devices.c:2148:2,
    inlined from 'Devices_RestoreEHWRIT' at devices.c:2173:2,
    inlined from 'Devices_IgnoreReady' at devices.c:2238:2:
/usr/include/bits/string_fortified.h:29:10: warning: 'memcpy' offset [0, 2] is out of the bounds [0, 0] [-Warray-bounds]
   29 |   return __builtin___memcpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I could not reproduce this in current master. Only way it could be a problem is if "address" was 0xFFFF.
Can you try adjusting the definition at memory.c, line 47, to:
```
UBYTE MEMORY_mem[65536 + 3];
```
Perhaps the abobe will help.


```
ui.c: In function 'DiskManagement':
ui.c:907:50: warning: array subscript -1 is outside array bounds of 'char[4096]' [-Warray-bounds]
  907 |                                                 q[-1] = '\0';
      |                                                 ~^~~~
ui.c:879:38: note: while referencing 'uncompr_filename'
  879 |                                 char uncompr_filename[FILENAME_MAX];
      |                                      ^~~~~~~~~~~~~~~~
```

This is a false positive - from line 890 and 891, q points to at least one past uncompr_filename, so q[-1] is always a valid pointer inside uncompr_filename.

```
In function 'strncpy',
    inlined from 'Util_strlcpy' at util.c:127:2,
    inlined from 'prompt_for_string' at monitor.c:2803:2,
    inlined from 'string_search' at monitor.c:2821:2:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
monitor.c: In function 'string_search':
monitor.c:2803:34: note: length computed here
 2803 |         Util_strlcpy(buf, input, strlen(input) + 1);
      |                                  ^
In function 'strncpy',
    inlined from 'Util_strlcpy' at util.c:127:2,
    inlined from 'string_search' at monitor.c:2829:3:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
monitor.c: In function 'string_search':
monitor.c:2822:15: note: length computed here
 2822 |         len = strlen(strbuf);
      |               ^
```

Yes, the length depends on the source, and the code could be simplified, but it is not a problem as both the source and the destination have the same allocated size, see monitor.c, 2794 for the first, 2813-2815 for the second one.

Have Fun!

**Comment by joysfera** [comment]
Too old.
