### ISSUE TITLE
Support 32MB ATR disk images

### ISSUE THREAD

**Issue by eahumada** [atari800/atari800#129]
It is possible to create 512 byte sector ATR files (RespeQt App) to use with SpartaDOS X. When one of this files is selected on atari800 on mac the emulator give the message that the file can not be opened, tested on version 4.2.0

**Comment by mikrosk** [comment]
@eahumada can you supply test files for given scenario?

**Comment by mikrosk** [comment]
@eahumada please supply the ATR and test it in Altirra. If that works, feel free to reopen.
