### ISSUE TITLE
Add support to compile to JavaScript with emscripten

### ISSUE THREAD

**Issue by eahumada** [atari800/atari800#130]
Request to add support to the atari800 emulator to be compiled to JavaScript using the [emscripten](https://github.com/kripken/emscripten/wiki) technique that is used by [jsA8E](http://zerstoerung.de/jsa8e/?disk_filename=river%20raid.atr) and [JSMESS](https://github.com/jsmess/jsmess/wiki/How-to-build-and-test-JSMESS-0.153). 

Currently there is not a JavaScript emulator for Atari XL that be practical to use to produce content and integrate in pages.

Use atari800 as JavaScript emulator could be great to the future creation of web based Atari content and development tools.

**Comment by eahumada** [comment]
As an additional comment: Having a JavaScript or WebAssembly target will be great to be able to generate live demos or online tools like the shown here: https://8bitworkshop.com/v3.7.1/?platform=atari8-800xl.mame&file=hellopm.dasm

**Comment by eahumada** [comment]
[Here](https://eahumada.github.io/AtariOnline/), a collection of live online programming environments for Atari 800XL, using jsA8E.

I fixed some missing keycodes but still gets crazy with some keystrokes if you type too fast. Online works well with US-american keyboard and the keys have the same location than in original Atari. Will be great to have an "official" release of the emulator on github with the steps and build scripts to go from the C to js as it could be a great tool to publish live Atari content in the web (as Javatari allow publish 2600 games). I tried [JavaScript-MAME](https://8bitworkshop.com/v3.7.1/?platform=atari8-800xl.mame&file=joyas.bas), but make funny noised on my computer. I hope that Atari800 emulator have an JavaScript or WebAssembly target in the future. I don't about any other Javascript for Atari XL/XE home computers.

I wonder if there is other people interested in publish live Atari web content, I imagine that there is a lot of possibilities (ex. online gaming, tutorials, 6502 assembly tutorials, logo online, connect to Atari BBS using R: device and websockets from a web page, etc).

https://eahumada.github.io/AtariOnline/

**Comment by mikrosk** [comment]
Patches welcome. ;)

**Comment by JeremyJStarcher** [comment]
I once submitted a patch that would allow this as part of an SDL-2 conversion.

That patch has now gone stale, however, and I am looking at manually merging it into the latest version from here.

**Comment by mikrosk** [comment]
@JeremyJStarcher feel free to create a PR. Closing as resolved.
