### ISSUE TITLE
Adding Cartridge Types and Bank Switching

### ISSUE THREAD

**Issue by ghost** [atari800/atari800#131]
If I were to edit the Cartridge.C and Cartridge.H files and add a 5200 cartridge type.  Are there any other modules that I need to modify throughout the program project to make it work? I am looking to add some cartridge types larger than 32K like the AtariMax flash cartidge, the ones "Bryan" posted about, and few others.

**Comment by mikrosk** [comment]
I'm not an expert on this area but I would say that if you add the code and given cartridge dumps start working, it's definitely a good sign. ;)

You can look at other cart-related commits, for instance: https://github.com/atari800/atari800/commit/4312d077d9a6fc8a5b4f4332e69c9cc87126754e ... there you can see that perhaps also `cartidge_info.{c,h}` and others should be updated.

**Comment by TheRobotFactory** [comment]
This may have been done in #106

**Comment by mikrosk** [comment]
Feel free to create a PR with your changes, we'll discuss there if something is missing. Closing.
