### ISSUE TITLE
2.0.2 runs too fast

### ISSUE THREAD

**Issue by thesnable** [atari800/atari800#132]
Hello!

I see that the Game is too fast, and that the sound is somewhat distorted.... is there something wrong with the emulator? Or ore there setting i can set to enable a "true" realtime emulation?

(Atari 800 XL)
WIth the latest (https://github.com/atari800/atari800) 4.2.0 on windows it runs perfect
I see that latest version for retro fw 2.2 (which i use) is 2.0.2 . Maybe thats the issue? The device is a gcwzero clone toolchainwise (RG-300)

Thanks alot!

**Comment by mikrosk** [comment]
Hi, I'm afraid you will have to contact the maker of given device/software package. 2.0.2 is really old, so even if it were Atari800's fault, nobody is going to investigate such an old release.

My advice would be to request an update on that retro fw side.
