### ISSUE TITLE
Android port apk

### ISSUE THREAD

**Issue by exebook** [atari800/atari800#135]
How can I find a precompiled apk for Android? I have checked all assets for each release, browsed everywhere on the website and skimmed all issues and was not able to find anything.

**Comment by VR51** [comment]
I'm curious about this too.

**Comment by joysfera** [comment]
https://play.google.com/store/apps/details?id=name.nick.jubanka.colleen

**Comment by VR51** [comment]
All these years I never realised Colleen was Atari800's alter ego. Going to try Colleen on Fire TV Cube.
