### ISSUE TITLE
Initial configuration with setting the ROM path doesn't take effect until new start

### ISSUE THREAD

**Issue by mikrosk** [atari800/atari800#15]
1. Start `atari800` without any config file
1. The Altirra BIOS is shown
1. F1 -> the main menu shows 'Atari 800 XL' as the computer emulated
1. Find your ROM directory, choose
1. Atari800 XL now shows correct ROM revisions etc
1. Shift+F5 (cold boot) --> you'd expect the OS ROM booted but nope, still the Altirra BIOS!

There are several workarounds possible, one is to exit the emulator but it's clearly a bug.

**Comment by kr0tki** [comment]
It is debatable if it is a bug or a poorly-described feature. Shift+F5 does not reinitialize the emulated machine, it only jumps to the OS Cold start vector, preserving the machine state, e.g. RAM under ROM is not wiped out. If we changed the behaviour to reinitialization of the whole machine, then this feature of RAM under ROM would have to go.

Note that one does not need to exit the emulator - the ROMs are reinitialised also when changing something in System Settings.

My proposed solution would be to:
1. Leave Coldstart as it is,
2. When user changes OS ROM paths, detect if the change influences the currently-running machine and ask him if he wants to reinitialise the machine.

**Comment by joysfera** [comment]
I would think that cold start = power off, wait 1 minute to loose all RAM content, power on. The name "cold" implies it's a power on from a totally cold state.

**Comment by mikrosk** [comment]
As nobody has taken a look during the two years, I have just fixed it.

It wasn't as trivial as I'd hoped (if one wants to avoid unnecessary restarts) but I'm pretty happy with it now.

I left the coldstart behaviour as is, mainly due to the fact it has always been like that and nobody has complained so far.
