### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by VR51** [atari800/atari800#153]
Why do you leave the version number at 4.2.0. The project has been at this version since December 2019 despite all the incremental updates made to the code base. This leaves some users like myself hopping between and computers and here to check we have the most up to date version of atari800. I think some users of atari800 might even ignore updates because they assume they already have the latest package installed. Just curious, why keep the version number at 4.2.0?

**Comment by joysfera** [comment]
Please use the Atari800 mailing list for general questions. Just FYI, version number increases at each release.
