### ISSUE TITLE
Unable to build 4.2.0 --with-video=no --with-sound=no on ubuntu:focal

### ISSUE THREAD

**Issue by SignumTemporis** [atari800/atari800#155]
I'm trying to build the project in a Docker:

```Dockerfile
FROM ubuntu:focal

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp
RUN set -euxo pipefail; \
    apt-get update && apt-get install -y curl; \
    \
    curl -L -O https://github.com/atari800/atari800/releases/download/ATARI800_4_2_0/atari800-4.2.0-src.tgz; \
    tar -zxf atari800-4.2.0-src.tgz

RUN apt-get update && apt-get install -y build-essential

WORKDIR atari800-4.2.0
RUN set -euxo pipefail; \
    ./configure --with-video=no --with-sound=no; \
    make
```

The build fails with the following message:

```txt
rdevice.c: In function 'open_connection':
rdevice.c:772:19: error: 'caddr_t' undeclared (first use in this function); did you mean 'in_addr_t'?
  772 |           memcpy((caddr_t)&peer_in.sin_addr, host->h_addr_list[0], host->h_length);
      |                   ^~~~~~~
      |                   in_addr_t
```

When I modify the `src/rdevice.c` file the following way:

```
772c772
<           memcpy((caddr_t)&peer_in.sin_addr, host->h_addr_list[0], host->h_length);
---
>           memcpy((char*)&peer_in.sin_addr, host->h_addr_list[0], host->h_length);
```

Then the project builds.

What may be wrong?

**Comment by joysfera** [comment]
This might explain it: https://stackoverflow.com/questions/6381526/what-is-the-significance-of-caddr-t-and-when-is-it-used

**Comment by SignumTemporis** [comment]
Strange. `caddr_t` is defined by `typedef` in line 117.

**Comment by SignumTemporis** [comment]
BTW, How to use the emulator in stdin/stdout mode? Will it work with BASIC (even simple scenario like 1 line of code + RUN)?

**Comment by SignumTemporis** [comment]
The code from `master` branch builds, so the issue itself may be closed.
However, I've still no clue how to use it the emulator in stdin/stdout mode.

```Dockerfile
FROM ubuntu:focal

SHELL ["/bin/bash", "-c"]

WORKDIR /tmp
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl unzip
RUN set -euxo pipefail; \
    curl -L -o atari800-master.zip https://github.com/atari800/atari800/archive/refs/heads/master.zip; \
    unzip atari800-master.zip

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y autoconf build-essential

WORKDIR atari800-master
RUN set -euxo pipefail; \
    ./autogen.sh; \
    ./configure --with-video=no --with-sound=no; \
    make
```

**Comment by SignumTemporis** [comment]
***REMARK***:
To build the emulator using the above `Dockerfile` and to install it back on `ubuntu:focal` host one can do the following:
```
docker build -t atari800 .
```
```
docker run --rm -v /usr/local/:/usr/local/ --workdir /tmp/atari800-master/src atari800 make install
```

**Comment by groessler** [comment]
On 12/22/21 12:25, SignumTemporis wrote:
>
> However, I've still no clue how to use it the emulator in stdin/stdout 
> mode.
>

What is your problem, what doesn't work?


$ (echo A ; echo D:) | 
~/classic/atari800/atari800-git/atari800-source/src/atari800.basic 
-nobasic ~/classic/atari800/aaaa/dos25-tests.atr
Using Atari800 config file: /data/home/chris/.atari800.cfg
Created by Atari 800 Emulator, Version 4.2.0

DISK OPERATING SYSTEM II VERSION COPYRIGHT 1984 ATARI CORP.

A. DISK DIRECTORY  I. FORMAT DISK
B. RUN CARTRIDGE   J. DUPLICATE DISK
C. COPY FILE       K. BINARY SAVE
D. DELETE FILE(S)  L. BINARY LOAD
E. RENAME FILE     M. RUN AT ADDRESS
F. LOCK FILE       N. CREATE MEM.SAV
G. UNLOCK FILE     O. DUPLICATE FILE
H. WRITE DOS FILES P. FORMAT SINGLE
SELECT ITEM OR  FOR MENU
DIRECTORY--SEARCH SPEC,LIST FILE?
   DOS     SYS 037
   DUP     SYS 042
   ATARI10 TGI 020
   ATARI11 TGI 020
   ATARI14 TGI 020
   ATARI15 TGI 020
   ATARI3  TGI 020
   ATARI4  TGI 020
   ATARI5  TGI 020
   ATARI6  TGI 020
   ATARI7  TGI 020
   ATARI8  TGI 021
   ATARI9  TGI 020
   ATR10P2 TGI 021
   ATR15P2 TGI 021
   ATR8P2  TGI 022
   MEM     SAV 045
   ATR9P2  TGI 021
   TGIDEMO COM 080
   SEPP    X   020
   SEPPI       020
   TTTT    BAS 001
   HEART   BAS 006
   HEARTS2 BAS 006
009 FREE SECTORS

SELECT ITEM OR  FOR MENU
$

> Message ID: ***@***.***> 

regards,
chris

**Comment by SignumTemporis** [comment]
When I run the emulator built `--with-video=no --with-sound=no` then Your example produces only this:
```
User config file '/root/.atari800.cfg' not found.
Trying system wide config file: /etc/atari800.cfg
No configuration file found, will create fresh one from scratch:
Writing config file: /root/.atari800.cfg
```

When I build with `libncurses-dev` and `--with-video=ncurses --with-sound=no` then the same example works and I get some output from DOS.

I suspect there is something wrong with the build configuration or libraries used but I don't know what.
