### ISSUE TITLE
Add authentic disk drive sounds

### ISSUE THREAD

**Issue by elsni** [atari800/atari800#158]
I'd love to have an option to turn on authentic disk drive sounds like in [altirra](https://www.virtualdub.org/altirra.html)

**Comment by mikrosk** [comment]
Duplicate of #110.

**Comment by elsni** [comment]
It is not a duplicate, I mean the mechanical noise (motor spin up, head seeking) of the 1050 disk drive, not only the SIO beeps.
as I mentioned, like in altirra (which is windows only, so no alternative)

**Comment by mikrosk** [comment]
Oh I see. Reopening then.

**Comment by mikrosk** [comment]
Actually, it is a duplicate of #110. After a second read of https://github.com/atari800/atari800/issues/110#issuecomment-646939592, it's clear that fully emulated SIO sounds imply also emulation of rotating disks. But I update the issue's title to make it explicit.
