### ISSUE TITLE
Compiler error on raspberry OS

### ISSUE THREAD

**Issue by elsni** [atari800/atari800#159]
latest version 4.2.0. 
run ./configure without parameter then "make"

CC       codecs/atari800-container.o
codecs/container.c: In function ‘CONTAINER_AddAudioSamples’:
codecs/container.c:260:12: error: ‘video_codec’ undeclared (first use in this function); did you mean ‘audio_codec’?
  else if (!video_codec) {
            ^~~~~~~~~~~
            audio_codec
codecs/container.c:260:12: note: each undeclared identifier is reported only once for each function it appears in
codecs/container.c: In function ‘CONTAINER_AddVideoFrame’:
codecs/container.c:314:14: error: ‘video_codec’ undeclared (first use in this function); did you mean ‘audio_codec’?
  if (!fp || !video_codec) return 0;
              ^~~~~~~~~~~
              audio_codec
codecs/container.c:322:21: error: ‘video_codec_keyframe_interval’ undeclared (first use in this function)
    keyframe_count = video_codec_keyframe_interval;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
codecs/container.c:332:64: error: ‘video_buffer’ undeclared (first use in this function); did you mean ‘audio_buffer’?
  size = video_codec->frame((UBYTE *)Screen_atari, is_keyframe, video_buffer, video_buffer_size);
                                                                ^~~~~~~~~~~~
                                                                audio_buffer
codecs/container.c:332:78: error: ‘video_buffer_size’ undeclared (first use in this function); did you mean ‘audio_buffer_size’?
  size = video_codec->frame((UBYTE *)Screen_atari, is_keyframe, video_buffer, video_buffer_size);
                                                                              ^~~~~~~~~~~~~~~~~
                                                                              audio_buffer_size
make[2]: *** [Makefile:2509: codecs/atari800-container.o] Error 1
make[2]: Leaving directory '/home/pi/source/atari800/src'
make[1]: *** [Makefile:1094: all] Error 2
make[1]: Leaving directory '/home/pi/source/atari800/src'
make: *** [Makefile:418: all-recursive] Error 1

**Comment by hatchcliff** [comment]
V4.2.0 and the current development version both compile OK for me on Pi OS, so we must be doing something different.

How did you obtain your copy of /atari800? 

Have you tried the following:
git clone https://github.com/atari800/atari800
cd atari800
Follow the instructions in DOC/BUILD.RPI to native compile.

**Comment by hatchcliff** [comment]
This discussion stalled 7 months ago, with no further reports of these compilation errors.

I haven't been able to replicate the problem, so can't see anything to be done.

I suggest closing the issue now
