### ISSUE TITLE
Split single package for Raspberry Pi into 2 

### ISSUE THREAD

**Issue by e474** [atari800/atari800#160]
Please ship 2 packages for the different Raspberry Pi architectures, having 2 binaries installed (and on the menu) makes no sense, and breaks the atari800 command for no good reason.

**Comment by hatchcliff** [comment]
#162 issued to revert to the method of packaging used in v4.2.0 (2 packages tailored to particular models of Raspberry Pi).

**Comment by hatchcliff** [comment]
Pull Request #162 has been merged, removing the tools used to produce the 2-binary package.
This is still being checked out, but it is likely that a single stock Linux package will be released for all supported models of Pi in future.  See comment in #162 concerning recent developments in Pi OS Bullseye for further details.
I think this issue could be closed now.
