### ISSUE TITLE
Atari800 version 5.0 crashes on ARM Linux

### ISSUE THREAD

**Issue by WizzardSK** [atari800/atari800#172]
Atari800 was upgraded to 5.0 on my Ubuntu system and now it crashes immediatelly after starting.

Kernel: 6.0
OS: Ubuntu 22.10, KDE desktop
Hardware: Acer Spin 513

![obrázok](https://user-images.githubusercontent.com/42868978/200120862-6e4f1d2f-18ca-4406-97a0-eb7c6a61a411.png)

It runs fine on my another x86 device so it seems like some ARM based bug.

**Comment by mikrosk** [comment]
Maybe try to delete/rename your old config file first?

**Comment by WizzardSK** [comment]
Wow! It indeed works! Thanks!

**Comment by joysfera** [comment]
@WizzardSK wish you made a copy of the old config file before deleting it so we could fix the obvious bug. The program should not crash...

**Comment by WizzardSK** [comment]
I did not, but I had just common customized config from 4.2 version, it should be easily reproducible.

**Comment by joysfera** [comment]
> I did not, but I had just common customized config from 4.2 version, it should be easily reproducible.

if you could reproduce it and then post the config file here it would be great.
