### ISSUE TITLE
RetroArch / LibRetro as officially supported platform?

### ISSUE THREAD

**Issue by ilmenit** [atari800/atari800#173]
Hi all,
There is an ancient version of Atari800 (3.1.0) used in https://github.com/libretro/libretro-atari800 . I know the issues and s*tstorms around RetroArch development and I wouldn't care about using RetroArch instead of the main emulator frontend, but there are retro handhelds, RetroPie and new ways to enjoy the Atari800 system. RetroArch seems to be a common denominator that is commonly used by Batocera, OpenDingux and other Linux based systems. Would you consider adding RetroArch/LibRetro as the first-class citizen platform? I could try to help making an integration layer, but only knowing that such work would have chance for being merged to the main branch.

**Comment by mikrosk** [comment]
I'm not aware of any s*storms around RetroArch. :-) What do you have in mind?

Generally speaking, if your patch doesn't break anything else or doesn't pollute code with hundreds of `#ifdef`s, I don't see any reason why it shouldn't get merged if it helps somebody.

**Comment by ilmenit** [comment]
Great, I will take a look how to add a compatibility layer not polluting too much the main code.

There's a lot of [controversy](https://www.reddit.com/r/emulation/comments/lnzpnt/can_someone_explain_why_people_hate_retroarch_now/) around RetroArch and disrespectful project lead, but RetroArch is nowadays a common denominator of emulators, so consistent user experience can be built on top of it.

**Comment by mikrosk** [comment]
The only point which got me worried is this: "Because the main dev does whatever he wants regarding licenses of the cores" - including Atari800 in RetroArch can be great for visibility but not if he'd stripping license terms and/or name of the project.

**Comment by ilmenit** [comment]
The situation about licenses I think got more settled now. Each core is a different codebase that should follow the license conditions of the project they base on: https://docs.libretro.com/development/licenses/
Atari800 is already there (for the old version). Many emulators (like [Fake08 for Pico-8](https://github.com/jtothebell/fake-08) ) have LibRetro as one of many supported platforms even when the core is not "managed" officially by RetroArch team. This allows to keep control in the hands of emulator devs and still benefit community for single interface on emulation devices that use RetroArch. That would be my approach for Atari800 emu - adding LibRetro as another supported platform.

**Comment by mikrosk** [comment]
Sounds good to me, go ahead then! :)

**Comment by ilmenit** [comment]
Btw, are devs on some real-time communication platform (Discord, Slack, Facebook etc.) so I could ask some questions during the development?

**Comment by mikrosk** [comment]
I'm on Slack and Facebook but usually it's a good idea to have such questions public so others can benefit, too. If you don't like to discuss it here, what about our mailing list https://sourceforge.net/p/atari800/mailman/atari800-users ?

**Comment by mikrosk** [comment]
Closing as resolved, feel free to create a PR when finished and/or ask questions on the atari800 mailing list.
