### ISSUE TITLE
Alt key doesn't seem to work in Linux AMD64 5.0.0 release.

### ISSUE THREAD

**Issue by thezerobit** [atari800/atari800#180]
None of the Alt or AltL key combinations seem to work, like Alt+R, Alt+D or LAlt+F, etc. It's not a show-stopper because all these commands are available from the built-in user interface menu reachable via F1, but it would be much more convenient to press LAlt+F to switch in and out of full screen instead of navigating through menus with arrow keys.

**Comment by mikrosk** [comment]
Are you sure that it isn't your desktop which is stealing the keyboard shortcuts?

**Comment by thezerobit** [comment]
I don't know why it would do that. Literally none of the Alt-? or LAlt-? shortcuts work, and they don't do anything in the desktop (KDE, I'm running Kubuntu). The only Alt-? desktop shortcut that works in the program is Alt-Tab which switches to another program only in windowed mode, that shortcut doesn't even work when atari800 is running in full screen. My desktop doesn't block other programs from using Alt-? shortcuts, so I'm not sure why it would with this one. I'll do some more research, though. One thing to note, if I hit Alt-F, atari800 will register it like a normal "F" keypress, same with others. It's like it doesn't even know the Alt key is being pressed at all.

**Comment by mikrosk** [comment]
https://community.linuxmint.com/tutorial/view/47 lists quite few of them.

However I did try it also on my Arch Linux (KDE flavour), latest Atari800 works fine there. I tried ALT+O and ALT+D.

Maybe you're pushing the wrong (right) ALT?

**Comment by joysfera** [comment]
Can you switch to GNOME for a moment to test it?
Can you try out a different keyboard?
What OS on what hardware are you running the Atari800 on?

BTW, it does not seem to be a bug in Atari800.

**Comment by thezerobit** [comment]
I'm running Kubuntu 22.04.1 on an ASUS Zenbook UX305. Unfortunately, I don't have Gnome installed. In the past, I haven't had a great experience installing multiple desktop environments (they interfere with each other), so I'm hesitant to install Gnome on top of a KDE system. I definitely tried both Alt keys and a whole bunch of different commands. I also plugged in an external USB keyboard, but that didn't change anything. There is a new version of Kubuntu (22.10), so I will upgrade and see if that fixes it. If nobody else is seeing this problem on Linux, then I imagine it is an issue with this version of Kubuntu and SDL 1.2.

**Comment by mikrosk** [comment]
As I don't have SDL 1.2 on my system anymore (only the compat layer for 2.x), I did quite a paranoid check - downloaded an emulator for 32-bit Atari, downloaded Atari800 5.0.0 for that platform (based on SDL 1.2) and tried the hotkeys there - it also worked.

So you see, if forwarding ALT+O to an emulator which then forwards it to an SDL which then forwards it to Atari800 works, I'd say everything is really bullet-proof. ;)
