### ISSUE TITLE
Keyboard mapping on linux?

### ISSUE THREAD

**Issue by peter099** [atari800/atari800#181]
I am using atari800 on MX Linux. How can i access keyboard mapping settings and change them?

**Comment by mikrosk** [comment]
Can you explain your use case, i.e. what are you trying to achieve, in more detail?

**Comment by peter099** [comment]
I found how to change keyboard shortcuts: F1 > Controller Configuration > Define layout of keyboard joystick.

But i have two issues:

Atari800 does not remember my changes. For example, if i change the keyboard buttons for movement to A,D,W,S next time i start the emulator they are reset to the default keys.

There is only option for movement keys and one key for fire, but some games require two keys for fire. For example, Super Cobra requires two fire button: bombs and machine gun.

**Comment by joysfera** [comment]
1. this GitHub Issues place is not a support forum. Atari800 mailing list is a better place.
2. Atari800 does not support general remapping of all ASCII keys. It emulates joystick on keyboard and that setting can be changed and of course must be saved if you want it to persist.

**Comment by peter099** [comment]
How to save changes in settings? I tried with `Save State` option and it created file in my home directory, but when i launch atari800 the changes are reset again.

**Comment by mikrosk** [comment]
There is a command in the main menu, along with the option to save it automatically on each exit. Take some time to inspect it.

As @joysfera said, this is better suited for the mailing list, so closing.

**Comment by joysfera** [comment]
@peter099 The saving option is unfortunately kinda hidden under Emulator Configuration. We should probably move it to the top level now when there are two other configuration submenus (Display and Controller).

**Comment by peter099** [comment]
I found the option to save settings on exit, so that's fixed.

So, it's not possible to add more than one fire button? I think RetroArch had option to add more than one fire buttons for atari800 core but i have to check.

I don't get why email is more suitable for support. Other people may have the same issues and this thread will be more easier to find than emails.

**Comment by joysfera** [comment]
GitHub is our tool for developing the software. If it got flooded with support questions it could block the development itself eventually, I am afraid.

In the mailing list there should be more people using the emulator and willing to help (in theory at least).

**Comment by peter099** [comment]
How to sign up for the mailing list and ask for support?

**Comment by mikrosk** [comment]
https://atari800.github.io/contact.html :)
