### ISSUE TITLE
Debugger: Is it possible to clear breakpoint(s)?

### ISSUE THREAD

**Issue by mirao** [atari800/atari800#182]
I can see that `BPC` or `BLINE` can set breakpoints.
But how to delete them?
Let's say I set `BLINE 63` and `CONT` - it breaks program at scanline 63.
Now I want to delete that breakpoint so that I can `CONT` and watch program behavior without debugging. How to do that?

**Comment by mikrosk** [comment]
Hmm, what happens if you type `BLINE 63` again?

**Comment by mirao** [comment]
@mikrosk 
It just set it again
```
> bline 63
Breakpoint set at scanline 63
```

**Comment by mikrosk** [comment]
I was close - it should work by setting bline to a negative number.

**Comment by mirao** [comment]
Found a solution, passing a number `> 311` disables it (which makes sense, at least for PAL). E.g. `312`
```
> bline 311
Breakpoint set at scanline 311
> bline 312
BLINE disabled
> bline 311
Breakpoint set at scanline 311
> bline -2
Breakpoint set at scanline 311

```

**Comment by mikrosk** [comment]
Actually there is a much better description available, perhaps by typing some kind of `help` or `?`:

```
printf(
			"B                - print breakpoint table\n"
			"B ?              - this help\n"
			"B C              - clear breakpoint table\n"
			"B D pos          - delete one entry\n"
			"B ON             - enable breakpoints\n"
			"B OFF            - disable breakpoints\n"
			"B ON pos1...     - enable specified breakpoints\n"
			"B OFF pos1...    - disable specified breakpoints\n"
			"B [pos] cond1... - insert breakpoints (at the specified position)\n"
			"    cond is: TYPE OPERATOR VALUE (without spaces)\n"
			"         or: SETFLAG, CLRFLAG where FLAG is: N, V, D, I, Z, C\n");
```

**Comment by mirao** [comment]
Well, interesting, don't know how to get a help for debugger commands. `help` or `?` show only a general help, not details about a specific command.
The command you wrote doesn't work. But at least `BLINE 312` works. Thanks.

**Comment by mikrosk** [comment]
Just to clarify: the mentioned "advanced" functionality is disabled by default. It's called "user-defined breakpoints" and one can enable it while building with `--enable-monitorbreakpoints`. So yes, your solution seems to be the simplest one available by default.

**Comment by mirao** [comment]
@mikrosk Thank you for much
