### ISSUE TITLE
Unable to Run Programs in RetroArch on Android - Several Crashes

### ISSUE THREAD

**Issue by 66dude** [atari800/atari800#189]
Hi,

I am using RetroArch on my OnePlus Nord N10 5G and using the atari800 core from within RA. Every time I load an Atari 800 program through RA, I get the familiar "need a real Atari" screen. I already have a button on my controller mapped to F1 so I can get to the emulator settings. Any time I attempt to run a program from within the emulator, it craps out and sends me back to my phone's home screen. Same thing happens when attempting to go to a directory containing the BIOS - navigating to the menu option to find a directory containing the BIOS also crashes the emulator and RA. Editing the .atari800.cfg file to point RA to the BIOS files has no effect because I don't know where to put the config file, and I am never sure if I am inputting the correct path to the directory containing the BIOS files. I don't have that issue with the Raspberry Pi. Thanks in advance for your time and assistance!

**Comment by 66dude** [comment]
> Oof, I guess this one can be answered by someone who knows something about both RA _and_ your device. Atari800 just asks for files, so the issue is more like "how to convince your device/setup to look for them at the right place" than a bug in Atari800.

I also tried this in my other phone, a Motorola G 5G, and I get the same exact issues. The OnePlus is running Android 11 and the Motorola is running Android 12. So I'm thinking it's an issue regardless of the phone used.

**Comment by mikrosk** [comment]
That's totally possible but you have to understand it's not who us packaging, testing and building for the phones in the first place. Atari800 is based on SDL which can be used on nearly any OS you can imagine, incl. your phone. So you have to contact either RA maintainer or the one who provided the executable for your phone. We have no way of testing and fixing this.
