### ISSUE TITLE
SuperDOS 5.1 hangs on boot due to disk emulation issues

### ISSUE THREAD

**Issue by phaeron1024** [atari800/atari800#190]
SuperDOS 5.1, from the archive attached to this post, hangs on boot on Atari800:
https://forums.atariage.com/topic/354163-superdos-offical-versions/?do=findComment&comment=5304664

The specific image is SDOS51US.ATR [CRC32 304E57EE], and it hangs on Atari800 cores from Atari800WinPLus 4.0 through the latest Atari800 5.0. There appear to be two issues causing this hang.

The first issue is that SuperDOS tries to use XF551 commands because of a successful read PERCOM block command ($4E), but Atari800 does not support the XF551 high-speed get status command ($D3). The emulator rejects the command, but the second issue is that it does so with a device error ($45) instead of a NAK ($4E). This causes common status completion handling in SuperDOS at $0967 to fall through and wait for a Complete/Error byte that never arrives. This causes about an 85 second wait per command retry since the OS timer 1 is set to 5120 vblanks.

**Comment by mikrosk** [comment]
Hi @phaeron1024, thanks for reporting this. However are you sure that you were looking at the latest `sio.c` when doing your analysis? 

I've briefly tested the image provided, the commands Atari800 replies to are:  $53, $52, $52, $52, $52, $52, $52, $52, $52, $52, $52 and finally $4e.

Then there's a huge pause, after which Atari800 replies to: cmd: $48 (NACK), $3f (NACK + TIMEOUT), $53, $53 and again $4e.

Again a huge pause, after which Atari800 replies to: $48 (NACK), $3f (NACK) and $53 followed by TIMEOUT, TIMEOUT.

Then the main menu is shown. Commands without parenthesis get SUCCESS as reply.

As I'm not 8-bit expert, can you perhaps give me a hint what is wrong there and/or what should Atari800 do instead?

**Comment by phaeron1024** [comment]
The command that follows the $4E (Get PERCOM Block) command is the high-speed status command ($D3). sio.c contains XF551 high speed handlers for high-speed read sector, for instance:

https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1181
https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1400

...but not for high-speed get status:
https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1207
https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1436

As for the hang, it's because of the wrong response to the unsupported $D3 command. Unrecognized commands are supposed to be returned with a NAK ($4E). sio.c does this for the SIO patch path:

https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1273

However, SuperDOS is not using the standard SIO routines when it needs to do high-speed I/O, so it is bypassing the SIO patch and driving POKEY directly. The command frame handler for this is returning the incorrect $45 code:

https://github.com/atari800/atari800/blob/70ab6aba601ce64bbed02bab99a5d824d0da2cbf/src/sio.c#L1487

In the SIO protocol, the command frame reply is always A/N, the data frame reply for a write is A/N, and the operation reply is C/E.

**Comment by mikrosk** [comment]
Many thanks Avery, obviously I was looking at the wrong place -- I wasn't aware of the SIO handler / POKEY access difference so I skipped `Command_Frame` in my investigation.
