### ISSUE TITLE
ROMs default location

### ISSUE THREAD

**Issue by maciejos78** [atari800/atari800#194]
Hello,

On Debian 12 in atari800 man stands, that default ROMs location is:

```
FILES
       /usr/share/atari800/ATARIOSA.ROM
              Atari O/S A

       /usr/share/atari800/ATARIOSB.ROM
              Atari O/S B

       /usr/share/atari800/ATARIXL.ROM
              Atari 800XL O/S

       /usr/share/atari800/ATARI5200.ROM
              Atari 5200 O/S

       /usr/share/atari800/ATARIBAS.ROM
              Atari Basic

```

In [README.Debian](https://github.com/atari800/atari800/tree/ATARI800_5_0_0/debian) on GIT the location is different:

```
You must have the ROMs to use this emulator. The system admin should
install the ROMS in **/usr/local/lib/atari/ROMS/** or anywhere else if you
adapt the configuration file (see the provided atari800.cfg)
```

When .atari800.cfg does not exist, the emulator checks for ROMs on path /usr/share/atari800 and fills ROMs entries in configuration.
When .atari800.cfg exists, but does not contain any values pointing ROMs, the emulator does not check for them in default location. Is it designed behave?

Regards
Maciejos

**Comment by mikrosk** [comment]
I think it is (except the wrong path in the readme). You may want to have an empty = current path as a valid search dir.

**Comment by mikrosk** [comment]
Whoa, this took way longer to investigate than I had anticipated:

- actually, both the man page and README.Debian are correct: the default search path for Atari800 indeed is `/usr/share/atari800` while the Debian maintainer indeed does override the paths as described: https://github.com/bobek/atari800-debian/blob/c21fe396629b8ab66a49ff335aa9dbbd18702520/debian/atari800.cfg#L2-L6
- what is more interesting, the README mentions also `/usr/local/lib/atari/DISKS` as a default path for disk images but this setting is completely lacking in the atari800.cfg. So if anything, I'd suggest to ping @bobek (Antonin Kral) whether he wouldn't be willing to update his `atari800.cfg` with `ATARI_FILES_DIR` set to `/usr/local/lib/atari/DISKS`.
- there used to be a default path for disk directory specified directly in `Makefile` but that is long gone. So currently only current dir is taken into account if `ATARI_FILES_DIR` is not specified.

**Comment by joysfera** [comment]
I feel like the disks don't need to be system-widely shared. Perhaps they should be in $HOME only, no /usr/*

**Comment by mikrosk** [comment]
They aren't, as mentioned we don't provide any default location for them. But we do have the concept of `ATARI_FILES_DIR` which is sort of default folder for your atari files, incl. disk images. So one can specify such dir in atari800.cfg if desired.

**Comment by bobek** [comment]
Actually, this dates waaaay back, it was definitely a part of the original package and got carried over ...

See https://github.com/atari800/atari800/commit/ff97396a743407de6a74adddecc7247b196cf4d4

I guess, the best would be to take `src/dc/atari800.cfg` directly.

**Comment by mikrosk** [comment]
@bobek `dc` is a dreamcast port. We don't provide a default atari800.cfg, it's created on first start.

**Comment by groessler** [comment]
Yes, the dc cfg file is required beforehand since it needs to be burned to the CD.
