### ISSUE TITLE
Keyboard joystick stuck UP

### ISSUE THREAD

**Issue by brad-colbert** [atari800/atari800#195]
Hi,

First, thank you for all of the hard work.

Host: Ubuntu 18.04
Standard build, no alternate switches.

My keyboard joystick 1 is stuck in the up state.  I'm not sure how to fix it?  Is this an issue with SDL?

Thank you,
Brad

**Comment by joysfera** [comment]
try the following:

$ sudo apt install jstest-gtk
$ jstest-gtk

**Comment by joysfera** [comment]
@brad-colbert how is your keyboard joystick 1 defined? What keys does it use?

**Comment by gagern** [comment]
What version are you building from? Is this the Ubuntu package or from more recent sources?

Personally I found https://github.com/atari800/atari800/commit/60ee439b38c5338d314d2cae2b7e86c4f0928eb2 a huge help in debugging input. It allows using the `-record` command line flag to capture the events as seen internally, then aggregate that efficiently. You should get rows of the form `-1 255 255 1 1 1 1` if no button are pressed. The first number is the keyboard key, the second is joystick 1&2 directions, the third joystick 3&4 directions, and then come the four triggers. All of these joystick numbers use bit `1` for default state and bit `0` for active state.

If the first joystick is stuck in the up position, that would show as `-1 254 255 1 1 1 1`. So if that is what you see, then yes, there is most likely a problem in the SDL layer. If on the other hand you get a `255` there, then it's either somewhere more central in the emulation, or even in the emulated application. For SDL here is the location where the key press gets translated into a joystick direction:

https://github.com/atari800/atari800/blob/c0d940eeb51b2652c0ec53ffe6e3c01a6f51877a/src/sdl/input.c#L1561-L1562

Adding debug output somewhere around that could help debug this.

Do you have any physical joysticks connected? If so, then by default the first physical yoystick would overlay the first keyboard. So if you happen to have a coffe mug standing on a button of the base of a physical joystick, that would also affect the device you want to control by keyboard. The `-joy-distinct` flag from https://github.com/atari800/atari800/pull/197 would help in this case.

**Comment by joysfera** [comment]
OP does not respond, closing.
