### ISSUE TITLE
Can't Mix ATX and ATR images on the command line

### ISSUE THREAD

**Issue by pcrow** [atari800/atari800#218]
If you start the emulator with two disk images on the command line, it works as expected if both are ATR files.  If the first image is an ATX file, and the second is an ATR file, only the ATR file is seen.  If they're in the other order, both are seen.  If you specify two ATX files, only one is seen.  This is frustrating when using a wrapper to pre-load all the disks for a game.

**Comment by mikrosk** [comment]
Thanks for reporting, it seems that for 15 years you have been the only one trying to load more than one ATX/ATR file. :-)

Fixed.

**Comment by pcrow** [comment]
Thanks for fixing.  I have a wrapper script that adds a scratch ATR image as a second disk in case I want to save something, but it didn't work when the main image was ATX.  I could also see this for a multi-disk game where only the first was protected, but that's not what I hit.
