### ISSUE TITLE
PIA emulation issue with Caverns of Mars

### ISSUE THREAD

**Issue by pcrow** [atari800/atari800#219]
When playing Caverns of Mars, the joystick fire button works, but the movement doesn't.  There was a discussion on Atari Age about this where someone figured out that the game does some really weird stuff with PIA.  Something like putting it in output mode while still reading back data.  I'm not clear on the details of the problem, but I'll include a link to the discussion.  Someone patched the game to avoid the problem, so anyone who finds this report can go to that thread to find the fix.

https://forums.atariage.com/topic/324607-caverns-of-mars-no-joy/

**Comment by dmsc** [comment]
Hi!

I could not reproduce it with the CAR posted in that thread.

Do you have a version that does not work?

Have Fun!

**Comment by pcrow** [comment]
[caverns.zip](https://github.com/atari800/atari800/files/14070810/caverns.zip)

Here's the file that worked on my 800.  I think this is from the APX version.

**Comment by dmsc** [comment]
Hi!

Works perfectly here, Atari800 5.2.0, emulating both an 800XL or an 800. I'm in Linux, using a self compiled binary.

What platform are you using?

Can you try after renaming your atari800.cfg file, to start with a default configuration?

Have Fun!

**Comment by pcrow** [comment]
This being a PIA issue, I tried it as a 130XE instead of an 800, and it works fine.  So 800 mode PIA emulation isn't perfect.  I knew this ran on my 800, so I hadn't thought of trying XL or XE mode.

**Comment by dmsc** [comment]
This is strange - I don't see the PIA issue at all - it works here in 800 and 800XL mode.

Can you send me your atari800.cfg file to try here?

What is your atari800 version?

Have Fun!

**Comment by dmsc** [comment]
Also, the thread you addressed is wrong - PIA emulation in Atari800 is correct, and already (and for over 24 years) takes into account that the inputs are read also when the direction is set to output and the output value is set to 1.

See https://github.com/atari800/atari800/blob/master/src/pia.c#L152

Have Fun!

**Comment by pcrow** [comment]
I'm currently running 5.2.0, but have tried with 5.0.0 and just now 4.2.0.  I eliminated everything but the OS ROM locations from the config file.  So knowing it works for you and not me, that's the obvious place to look.  The MD5 checksum on my 800 ROM doesn't match what is found online, so it's some patched ROM I downloaded many years ago.  Switching to the real ROMs works.

Avoid these OS ROMs:
```
eb1f32f5d9f382db1bbfb8d7f9cb343a  ATARIOSA.ROM
a3e8d617c95d08031fe1b20d541434b2  ATARIOSB.ROM
```
Searching on those checksums finds a thread where someone reports, "It comes from PC XFormer, it was modified specifically to work with that emulator."

I had been meaning to download a full ROM collection, so now I'll do that.

So I'm sorry to have sent you on a wild goose chase.  I'll go back to the original thread that indicated it was an emulator problem and try to complete the circle.  At least if anyone else hits this bug, it will now be documented in all the right places.

**Comment by dmsc** [comment]
Wow, I did not expect that a patched ROM was the culprit !!

Great that you found it, thank you for the investigation :-)

Have Fun!

**Comment by pcrow** [comment]
I was certainly a surprise to me.  The Gentoo installation is getting ROMs from:
https://sourceforge.net/projects/atari800/files/ROM/Original%20XL%20ROM/xf25.zip
That explains why I had the ROMs I did.

**Comment by joysfera** [comment]
I didn't know the XFormer ROM was patched. Now I am curious how it was modified, what's different compared to the original one.

**Comment by mikrosk** [comment]
> Avoid these OS ROMs:
> 
> eb1f32f5d9f382db1bbfb8d7f9cb343a  ATARIOSA.ROM
> a3e8d617c95d08031fe1b20d541434b2  ATARIOSB.ROM
> Searching on those checksums finds a thread where someone reports, "It comes from PC XFormer, it was modified > specifically to work with that emulator."

Just to clarify this a bit more. The only custom ROM supplied with PC Xformer 2.5 is ATARIOSB.ROM. You can verify this in Atari800's OS ROM locations menu, this one is listed as "custom" while all the others are proper OS dumps. ATARIOSA.ROM is not even supplied with Xformer.

Nevertheless, the issue on the Atari 800 machine is indeed real. Maybe we should correct / mention this in our documentation (there are numerous doc files linking to xf25.zip as the legal way to download the ROMs) ?

**Comment by dmsc** [comment]
The problem is that the ROM posted above (a3e8d617c95d08031fe1b20d541434b2) was patched by removing the PIA clearing on boot - this means that the PIA starts in an invalid state. I think that the rom was patched to work as a soft-rom in an XL machine, to avoid writing over the PORTB registers.

Have Fun!
