### ISSUE TITLE
Using real disk drives with the emulator

### ISSUE THREAD

**Issue by TheMontezuma** [atari800/atari800#22]
I wondered if somebody could implememt such feature.
A floppy would be connected via 1050-2-PC cable (http://pages.suddenlink.net/wa5bdu/1050.txt).

I spent a few hours to implement a quick hack, but was not really successful:
https://github.com/TheMontezuma/atari800/blob/real_disk/src/sio.h
https://github.com/TheMontezuma/atari800/blob/real_disk/src/sio.c

A user would select /dev/ttyUSB0 (or something else depending how your 1050-2-PC cable is visible) as D1 under Disk Management. I tried to implement two approaches: with and without the SIO patch, 
however only with fixed 19200 baudrate support on the serial port side.
Instead of a real drive I tested the RespeQt floppy emulation (connected via SIO2PC cable) and could see data transfer with a logic analyzer, but there were command frames repetitions, etc., so I gave up on that...

**Comment by groessler** [comment]
Do you know where I could get a ready-made 1050-2-PC cable? I'd like to get one with real RS232 connector, not USB.
What other (driver-) software is needed on the host? I'm using Linux.

**Comment by TheMontezuma** [comment]
There are 3 possible diagrams here:
http://atariki.krap.pl/index.php/1050-2-PC

But the easiest way would be to use USB2SERIAL adapters (2 items) and build a "CROSS OVER" cable with two USB plugs on both ENDS:
GND - GND
TXD - RXD
RXD - TXD
CTS - RTS
RTS - CTS

One END "connected to" the emulator.
The other END "connected to" the emulated floppy:

The communication lines can be sniffed with a LogicAnalyzer.

You may consider to use the floppy emulation software "RespeQt":
https://github.com/jzatarski/RespeQt

**Comment by joysfera** [comment]
The other end connected to **emulated** floppy? I thought it was for connecting *real* floppy...

**Comment by TheMontezuma** [comment]
Well, before you spend effort to setup and connect a real floppy, you can help yourself with a floppy emulation, running on the same PC :)

**Comment by go2tom42** [comment]
> The other end connected to **emulated** floppy? I thought it was for connecting _real_ floppy...

True that is what they are using the SIO2USB device for, but that device would be needed to go the other way too.  You still need to convert SIO signal to a USB signal

**Comment by joysfera** [comment]
Apparently there is nobody interested in implementing that so I'm closing it for now. If somebody comes up with a patch / pull request we can reopen it.
