### ISSUE TITLE
TheCXStick Issue

### ISSUE THREAD

**Issue by JoeDonuts1011** [atari800/atari800#227]
Just purchased TheCXStick.

Wonderful feel, except that they added extra buttons around the orange ring of the joystick, as well as another button at the lower corner below the fire button.  This causes the fire to be pressed whenever you come in contact with the ring or the lower corner button, and makes game play difficult.

Outside of opening the stick and disconnecting, is there any way the emulator can be modified to unmap these buttons?

At present, I don't see anything in the emulator that allows for specific game controller mapping.

Thank you.

**Comment by mikrosk** [comment]
The interesting question here is: are those buttons even possible to map separately? Do you have a software which allows you to specify to use the main FIRE button but ignore the others at the same time? (most likely you do, just making sure that those buttons aren't all wired together)

**Comment by JoeDonuts1011** [comment]
I believe they can be mapped separately. As I am not the designer of the CX Stick, and only a customer, it would be great if there was any kind of options to direct map the CX Stick. This is a brand new product, and it’s all over YouTube. For now - I have done my own mods, and have removed the 4 ring buttons and the corner button.  Took a dremel wheel and removed the 4 plastic plungers for the 4 ring buttons, and completely unsoldered and removed the corner button from the PCB. Am hoping the manufacturer releases a stick that has no extra buttons as a variation of this stick.  All games for 8 bit Atari were designed with this joystick - no more than one button. Thank you for your response. Sent from my iPhoneOn Apr 20, 2024, at 9:58 AM, Miro Kropáček ***@***.***> wrote:﻿
The interesting question here is: are those buttons even possible to map separately? Do you have a software which allows you to specify to use the main FIRE button but ignore the others at the same time? (most likely you do, just making sure that those buttons aren't all wired together)

**Comment by mikrosk** [comment]
That's what I call dedication to the cause. ;-)

Okay then, if you find out more details (e.g. verify that the buttons are mapped separately) or anyone else bumps into this problem (from time to time we get questions of remapping keys), perhaps we'll look into this in depth how it could be done.
