### ISSUE TITLE
[Libretro Retroarch] Atari800 upstream

### ISSUE THREAD

**Issue by KamiLordus** [atari800/atari800#228]
The current libretro version of atari800 is the old version 3.1. Is there a chance to update it to the latest 5.2?

**Comment by mikrosk** [comment]
This is a question for the RetroArch project, not us. :)

**Comment by KamiLordus** [comment]
Too bad. Unfortunately, the person who made the Atari800 version for the retroarch platform shows no sign of life. So I'm left with version 3.1.

**Comment by mikrosk** [comment]
It's not rocket science, basically you just have to find someone in that project to take a look, no Atari knowledge is required here. Very little (if anything) has changed in Atari800's APIs during all those years.

**Comment by KamiLordus** [comment]
I also opened a query on the Atari800 libretro github page. But the chance that someone will look at it is less than zero :)
I will try to ask on the retroarch forum. Although the moderation doesn't like questions about core updates.
