### ISSUE TITLE
How do I get out of the "Fullscreen"?

### ISSUE THREAD

**Issue by TonVH** [atari800/atari800#23]
No matter what I do I cannot get into the preferences to turn fullscreen off. I even deleted the program and reinstalled but it keeps in fullscreen. 

What to do?

**Comment by Oli72** [comment]
Are you on Linux?
What version of atari800 are you using?
Alt-F does not work?
Have you tried to delete ~/.atari800.cfg?

**Comment by TonVH** [comment]
Hi,

Solved my fullscreen problem.

However, I am trying to get a gamepad working. But I absolutely do not understand the Help how to install it in preferences. Can you help. Picture of the gamepad is included. In principle I need the (left) cursor control and middel select, start buttons to work.


Thanks for your time.

Gr,
Ton

**Comment by joysfera** [comment]
Consider using our mailing list for user support.

**Comment by TonVH** [comment]
What is the URL for that?

**Comment by joysfera** [comment]
https://atari800.github.io/contact.html

**Comment by TonVH** [comment]
Sorry, but the link there leads to "https://sourceforge.net/projects/atari800/lists/atari800-users <https://sourceforge.net/projects/atari800/lists/atari800-users>” and produces:

**Comment by joysfera** [comment]
Sourceforge.net is apparently broken right now. Oh well.

**Comment by joysfera** [comment]
Original issue with leaving the fullscreen mode got resolved so I'm closing it.
Sourceforge mailing list is up and running now, so please direct your user questions there.
