### ISSUE TITLE
Keyboard Joystick keys are disabled in Basic

### ISSUE THREAD

**Issue by CJeUv** [atari800/atari800#235]
The keys specified in the layout are Disabled while in Basic.  When pressed there is NO click and nothing on the screen but value of the Stick location changes to the direction of the key pressed.  There is no reason that these keys should be Disabled.  Where in the code does this Disabling take place?

**Comment by mikrosk** [comment]
Sorry but I'm not entirely following. As in #234 please provide details about your platform and Atari800 version. And in addition to that:

> The keys specified in the layout are Disabled

What keys? What layout?

>  value of the Stick location changes to the direction of the key pressed

You mean that joystick emulation works?

> Where in the code does this Disabling take place?

I can't tell without further details what are you talking about.

**Comment by CJeUv** [comment]
Current Version 5-2-0
Raspberry Pi 3B running Raspberry Pi Bookworm up to date
SDL is part of Atari800 5-2-0

Controller Configuration - Enable keyboard joystick 1:  Yes - Define layout of keyboard joystick 1 - Select joy direction - The 5 keys there are the 4 arrow keys and right ctrl.
Run Atari Program - DOS with exit to Basic.  In Basic the arrow keys are disabled, No click and no positioning of the cursor.  But if you check the Basic memory location 632 the various values for the 4 directions are being generated, so the keys have been disabled to Basic but would work for a program reading memory location 632.  But in Basic you must have the ability to move the cursor to a previous line in order to edit that line.  There is no reason that the configured Joy Stick keys should be disabled in Basic.

**Comment by dmsc** [comment]
Hi @CJeUv !

Lets me explain:

- The Atari computers don't have cursor keys - see the image at: https://substackcdn.com/image/fetch/f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F43c0bbce-b90e-41db-a182-cf06e08a3d21_4032x3024.jpeg
- You can move the cursor, by pressing CTRL -/+/*/=, or in the Atari 1200XL (and only there), pressing F1 to F4.
- The emulator, as a convenience, maps the PC cursor keys to the F* keys.
- If you enable "cursor joystick", the PC arrow keys are mapped to the joystick, so they don't emit the cursor movement keystrokes.
- On an extended PC keyboard, there are two sets of arrow keys, you can map one set to the cursor keys and the other to the joystick.
- You can't map a PC key to two different actions, this will be very confusing and break many use cases.

Have Fun!

**Comment by CJeUv** [comment]
Atari computers do have cursor keys.  Pressing CTRL and one of the 4 keys are cursor keys, the cursor moves UP one line when CTRL-Minus is pressed.
Joy Stick 2 configuration has W,A,S.D configured and when Joy Stick 2 is YES then in Basic W,A,S,D are disabled, NO click nothing.  It is not possible to do anything in Basic with keys disabled.

**Comment by CJeUv** [comment]
I'm not sure who has to re-read what.
To be clear, Basic with disabled keys or no keyboard Joy Stick is NOT usable.
The 800XL (all Atari's) have 4 keys marked with arrows, the arrows are cursor control NOT Joy Stick control.  The 4 keys have 12 functions:
   Normal     -        =          +          *    
   Shift          _        |          \           ^    
   Conjtrol  Up   Down   Left   Right   
The emulator (atari800) has the 1st 8 keys already available at the PC keyboard locations.  The Cursor controls Up, Down, Left, Right should be available by Ctrl+ the Arrow keys on the PC keyboard.  The Joy Stick controls are Normal arrow keys.   There is no need to map the 1st 8 keys again on the arrow keys, just adds complexity and confusion.

**Comment by mikrosk** [comment]
> The Cursor controls Up, Down, Left, Right should be available by Ctrl+ the Arrow keys on the PC keyboard.

Sorry but this is only your personal opinion. At some point Atari800 developers made the decision to map PC cursor keys to _either_ `CONTROL` + `-`/`+`/`*`/`=` (as a convenience tool for easier text navigation) _or_ to a joystick (by default, can be changed). Other than that, the keys are unused because they are not present on Atari XE/XL computers.

You are free to disagree with this approach and you can even argue that not `-`/`+`/`*`/`=` should be treated as the keys where Atari XE/XL's arrow symbols are present but the PC arrow keys instead but unless you supply a patch to make this freely configurable or convince some developer to do it for you, you are stuck with the current approach.

Personally, I don't see much benefit in such change: if an Atari program asks you to press `SHIFT` and `*`, I certainly wouldn't be expecting to press `SHIFT` and left arrow on my PC keyboard.

**Comment by dmsc** [comment]
Hi!

>  The emulator (atari800) has the 1st 8 keys already available at the PC keyboard locations. The Cursor controls Up, Down, Left, Right should be available by Ctrl+ the Arrow keys on the PC keyboard. The Joy Stick controls are Normal arrow keys. 

My keyboard only has one set of arrow keys, as most laptop and small keyboards have.

If yours has two sets, then you can map the extra arrow keys as the joystick, and then the original arrows will work as keyboard input:
![image](https://github.com/atari800/atari800/assets/5713395/db16fe63-77dd-4900-bd7a-919754223f05)

then:

![image](https://github.com/atari800/atari800/assets/5713395/3bb89681-0564-4c2f-af1d-02598df5be67)

So, this is not really a bug.

Have Fun!
