### ISSUE TITLE
4 joysticks in Linux for Atari 800

### ISSUE THREAD

**Issue by severach** [atari800/atari800#25]
How to get 4 joysticks in Linux using [Super Joy Box 5](http://www.mayflash.com/Products/PCUSB/PC039.html)? I enabled multijoy but 4 sticks don't appear and the first 2 sticks stop working. The game is not multijoy compatible.

I have 3 sticks attached.

````
Using Atari800 config file: /home/chris/.atari800.cfg
Created by Atari 800 Emulator, Version 3.1.0

joystick 0 found!
joystick 1 found!
Video Mode: 1344x896x32 windowed without vsync
Unexpected command frame at state 60.
````

**Comment by joysfera** [comment]
I remember myself implementing support for four joysticks but I can't recall if I ever committed it.

**Comment by joysfera** [comment]
OK, @severach, if the joy is not multijoy compatible no wonder it does not work with multijoy emulation.
Atari XL/XE got two joysticks only. Are you going to play a game for old Atari 400/800/5200?

**Comment by joysfera** [comment]
Please tell me the name of the game so I could test it by myself.

**Comment by severach** [comment]
Mule on OSB.

**Comment by joysfera** [comment]
I think it works OK in version 4.0:
```
Using Atari800 config file: /home/joy/.atari800.cfg
Created by Atari 800 Emulator, Version 4.0.0

Joystick 0 found
Joystick 1 found
Joystick 2 found
Joystick 3 found
Video Mode: 336x240x32 windowed without vsync

```

**Comment by severach** [comment]
A 3rd joystick is detected but the joystick detection has changed substantially from 3.1 to 4.0. Super Joybox 5 PS 2 sticks are no longer functional. MULE detects every stick as a paddle where some sticks (paddles) always have their buttons held down.

**Comment by joysfera** [comment]
I have just tested it using the following BASIC code:
```basic
10 ? STICK(0),STICK(1),STICK(2),STICK(3)
20 ? STRIG(0),STRIG(1),STRIG(2),STRIG(3)
30 GOTO 10
```
I've plugged in good old Quick Shot II into all four joystick ports and it all worked great - all directions and all trigger buttons. The emulator code is definitely correct.

Maybe you can instruct your Super joystick or its driver to remap the functions so that the sticks do what they are supposed to do. It can be tested by independent test programs (say in Linux ```jstest-gtk```).
