### ISSUE TITLE
Version 4.0 release still reports as version 3.1.0

### ISSUE THREAD

**Issue by ChoccyHobNob** [atari800/atari800#27]
Title says it all really. The window title and menu title still say 3.1.0

**Comment by joysfera** [comment]
Could you please double-check on that? The version comes from src/configure.ac and that file in github has version 4.0.0.

**Comment by ChoccyHobNob** [comment]
My bad, I did a make clean but never ./autogen.sh or ./configure looks ok now

Shouldnt the makefile get removed when you make clean?
