### ISSUE TITLE
add remaining keymappings (Android port)

### ISSUE THREAD

**Issue by 89d** [atari800/atari800#40]
Attached is a patch that adds mappings for the unmapped keys in the Android port (Colleen), making it actually useful for more than games.  Only tested with the Hacker's Keyboard app, though it should also work with the AnySoft Keyboard app or a physical one.  Here are the new Android to Atari mappings:

Left Ctrl - Ctrl
Ins - Insert character (Ctrl+>)
Shift+Ins - Insert line (Shift+>)
Del - Delete character (Ctrl+Back S)
Shift+Del - Delete line (Shift+Back S)
Home - Clear (Ctrl+< or Shift+<)
Esc - Esc
Brk - Break
NumL - Caps

(NumL added as a Caps toggle key because the Hacker's Keyboard won't recognize a shifted backquote, so there was no way to re-engage uppercase mode.  Shift+Tab (Set Tab) and Ctrl+Tab (Clear Tab) already worked once the Ctrl key was mapped.)
[colleen_add_keymaps.patch.gz](https://github.com/atari800/atari800/files/2274856/colleen_add_keymaps.patch.gz)

**Comment by 89d** [comment]
Please disregard the above patch and use the attached updated version instead.

I realized there were still several key combinations needed for the Action! editor that couldn't be typed on the Hacker's Keyboard, so I added these additional Android to Atari mappings (Action!  editor functions in parentheses):

Ctrl+Shift+Del - Ctrl+Shift+Back_S (join to previous line)
Shift+Left - Ctrl+Shift+< (move to beginning of line)
Shift+Right - Ctrl+Shift+> (move to end of line)
F11 - Ctrl+Shift+1 (change to window 1)
F12 - Ctrl+Shift+2 (create/change to window 2)

I believe all the Action! editor commands are now usable on Colleen.

I also added mappings for function keys to Atari console keys in XE keyboard order:

F1 - Help
F2 - Start
F3 - Select
F4 - Option
F5 - Reset (warmstart)
Shift-F5 - Reset (coldstart)
F7 - Break

I added a preference to switch to the Atari800 ordering for those who prefer it.

[colleen_add_keymaps-2.patch.gz](https://github.com/atari800/atari800/files/2363006/colleen_add_keymaps-2.patch.gz)

**Comment by mikrosk** [comment]
@89d Please create a pull request so our life will be a bit easier and credit to your work kept.

**Comment by mikrosk** [comment]
I shouldn't have dismissed this so quickly. So 6 years later I bit the bullet and re-applied those manually. Thanks @89d and if you can, give it a test in the next release. :)
