### ISSUE TITLE
portrait-mode hacks (Android port)

### ISSUE THREAD

**Issue by 89d** [atari800/atari800#41]
Using the Android port (Colleen) in portrait mode with the on-screen keyboard was difficult because the top of the Atari screen and the console key overlay would be covered by the status/action bars.  Attached is a patch that adds a preference for setting a padding distance from the top of the screen when in portrait orientation.  (Ugly, but much easier than figuring out how tall the status/action bars are programmatically on N different versions of Android.)

As there can now be room above the screen, another preference was added to adjust the console key overlay fade-out rate or disable it entirely so the overlay always stays visible.

Combined with my previous keyboard mapping patch, this patch finally makes Colleen useful for on-the-go 8-bit programming.
[colleen_portrait_hacks.patch.gz](https://github.com/atari800/atari800/files/2274961/colleen_portrait_hacks.patch.gz)

**Comment by 89d** [comment]
Oops, accidentally left a second copy of the Fade-out preference under Sound.  Please use this patch instead.
[colleen_portrait_hacks-2.patch.gz](https://github.com/atari800/atari800/files/2275618/colleen_portrait_hacks-2.patch.gz)

**Comment by mikrosk** [comment]
Made a PR in #59.

**Comment by joysfera** [comment]
@89d would you mind mailing me the binary of upcoming release so I could place it next to other release files, please?
