### ISSUE TITLE
build fails if SUPPORTS_CHANGE_VIDEOMODE is defined but NTSC_FILTER is not

### ISSUE THREAD

**Issue by 89d** [atari800/atari800#43]
In artifact.c, need_reinit is only declared when SUPPORTS_CHANGE_VIDEOMODE and NTSC_FILTER are both defined, but it is later used without checking whether the latter is defined.  Patch is attached.

[ntscfilter.patch.gz](https://github.com/atari800/atari800/files/2300059/ntscfilter.patch.gz)

**Comment by joysfera** [comment]
I have implemented it manually in f3234a061c70f61c55dd4ad497239c34827a231f. Thanks, @89d.
