### ISSUE TITLE
Android retroarch crash

### ISSUE THREAD

**Issue by envirotech** [atari800/atari800#44]
Can't get it working on android tv box (ARMv7 Marshmallow v6.0.1; "1.7.4-Atari800 3.1.0 d52535f").  Have all the proper bios roms in the retroarch system folder. First I tried with my zipped roms, then with a few extracted to bin files, with no luck. Just crashes retroarch and error message "unfortunately, retroarch has stopped working".   Seems some other folks are having this issue too: forums.libretro.com/t/atari800-core-crashing-on-android/16099

**Comment by ChoccyHobNob** [comment]
You should be asking the retroarch devs, not the atari800 devs. The atari800 devs are not responsible for the retroarch cores.

**Comment by envirotech** [comment]
Thanks.  When I go to the retroarch page it indicates that issues are not to be posted regarding core bugs, though...

**Comment by envirotech** [comment]
Thanks for your help!
