### ISSUE TITLE
autogen.sh is now above atari800/src. Installation doc needs to be updated.

### ISSUE THREAD

**Issue by VR51** [atari800/atari800#45]
The file DOC/install is now out of date since you moved autogen.sh above atari800/src. This happened with the last commit. The new installation instructions should read:

```1. Change your working dir to the atari800 path
2. Check if "configure" script is there. If it is skip to step 4.
3. Run "./autogen.sh" (make sure you have autoconf >= 2.5x installed).
4. Type "./configure".
5. Type "make".
6. Change directory to atari800/src
7. Install the emulator by typing "make install".
```

Notice the change to line 1, the addition of line 6 and the budging up of the last line to line 7.

Either the install doc should be updated and (?) install-sh (?) updated to point `make install` to atari800/src or autogen.sh should be moved back into atari800/src.

**Comment by joysfera** [comment]
@mikrosk ?

**Comment by mikrosk** [comment]
I guess `autogen.sh` is in toplevel because `src` isn't the only folder with generated `Makefile`. So unless @th-otto disagrees, it makes sense to update the documentation. What was `install-sh` used for?

**Comment by VR51** [comment]
I got the impression install-sh is used somehow in the autogen process to set the directories. I'm probably mistaken about that.

The only reason I noticed the change of location for autogen.sh is that some months ago I wrote a script for Linux to download the files and install atari800. The script alerted me to the change when it failed to output the binary. You can view it here if you want to take a look: https://github.com/VR51/Atari800-Installer.

Thank you for keeping atari800 up to date. I like that the BIOS files no longer need to be downloaded separately. I use the emulator infrequently but so far the new version (with pre-installed BIOS) works well for the games I've played so far. Electroglyde works flawlessly.

**Comment by th-otto** [comment]
autogen.sh should be in the toplevel just like configure.ac, because it is then also used to determine the top level directory when you build outside of the source tree.
install-sh is used during "make install" as a wrapper for the install executable, which sometimes (on bsd systems i think) has non-standard options.
