### ISSUE TITLE
Error in color display on RPI

### ISSUE THREAD

**Issue by pik33** [atari800/atari800#52]
On Raspberry Pi while in GTIA mode (for example Rzóg Plazma in Bitter Reality or Compy Shop The Graphic demo von Peter Sabath) colors which should be brightest (luminance=15? ) are displayed in black. This destroys the look of the demo.

The effect doesn't exist in Windows version of Atari 800.

The RPi version is 4.0.0 complied from the source on Raspberry Pi several days ago.

**Comment by pik33** [comment]
It seems I found and corrected the error. To be tested.Simple basic test with plots in gr.9  works 

In the fragment shader,multiply the color (p0.r) by 255/256

**Comment by joysfera** [comment]
Merged. Thanks!
