### ISSUE TITLE
R: device not available on Linux

### ISSUE THREAD

**Issue by jakubpas** [atari800/atari800#54]
I am trying to enable R: device while configuring on linux:

./configure --enable-rserial --enable-rnetwork 

but I get:

Using R: device?......................: no

Is it broken or I miss some additional headers/libraries?

**Comment by joysfera** [comment]
add `--enable-riodevice` if you want to enable R: device.

**Comment by jakubpas** [comment]
Thanks a lot!

**Comment by jakubpas** [comment]
Still, I guess there is an error there. When I configure with --enable-riodevice I get:

```
rdevice.c:84:2: error: #endif without #if
 #endif
```
Looks like there is stray endif there. If I remove it then it compiles ok. 

When I try to run app: 

`sudo atari800 -rdevice /dev/ttyS0` ( I need sudo to access device)

atari800 hangs with no output in logs

**Comment by joysfera** [comment]
The `#endif` issue has just been fixed.
