### ISSUE TITLE
Errant --run on LST file containing 0x0A

### ISSUE THREAD

**Issue by thinkyhead** [atari800/atari800#55]
The emulator doesn't correctly import LST files with the `-run` parameter when there are `0x0A` or `0x0B` characters in the file, even though it can be discovered that `0x9B` is being used as the end-of-line character in the file.

The solution is for `atari800` to pre-scan the first lines of the program to see if `0x9B` is being used (double-checking that it appears in front of line numbers as an extra confirmation). If `0x9B` is in use, then `atari800` shouldn't convert any `0x0A` or `0x0B` characters into `0x9B` on the load.

I tried to generate a `.LST` file with `E."H:PROGRAM.LST":RUN` in it and run that instead, but the emulator doesn't like the `ENTER` command being used at the same time as `-run` since they use the same facilities.

**Comment by mikrosk** [comment]
Some background info: LST files have lines terminated by $9B (EOL) byte. Normally = stored on H1: for instance. However if we store such file on H5:, lines are terminated by CR/LF combo.

However if a file stored on H1: contains lines(s) with CR or LF (and still it is terminated by $9B), atari800 interprets it as a CR/LF file and not a $9B one. Also, we have to check whether the opposite scenario (having proper CR/LF with a $9B somewhere) works.

`Devices_ReadBasicFile` is the function to look into.

**Comment by mikrosk** [comment]
> The solution is for atari800 to pre-scan the first lines of the program to see if 0x9B is being used (double-checking that it appears in front of line numbers as an extra confirmation)

Actually this would be still very error-prone. Imagine having a CR/LF file with text like "<$9B>100<$9B>blah blah,<$0d>,<$0a>" - this would be still considered an Atari file and not a PC one.

In #78 I have implemented a much better (IMHO) heuristics, we just read the _last two_ bytes and determine the line ending according to those.

I'm not very familiar with this BASIC stuff, so anyone could confirm this is a sane thing to do, I'd merge it after that.

**Comment by thinkyhead** [comment]
Oh hi! I sometimes forget this project exists and the Notifications got buried.

I'll have a look at your heuristics fix. I hope to get back to these tools at some point. I was going to do reference implementations of the BASIC parser so that I can just compile AtariBasic into .BAS files, and go back through and improve things further.
