### ISSUE TITLE
./configure && make dist contains two .deps folders

### ISSUE THREAD

**Issue by mikrosk** [atari800/atari800#66]
The resulting archive is supposed to contain everything needed to build atari800 via `./configure && make`, however it seems to contain two useless folders:

`util/.deps`: guess_settings-guess_settings.Po, libatari800_test-libatari800_test.Po
`src/libatari800/.deps`: exit.Po, init.Po, input.Po, main.Po, sound.Po, statesav.Po, video.Po

Not a terrible bug but still annoying. Just in case @th-otto or anyone else smart enough wanted to take a look.

Until then, @joysfera should be careful when making a release.

**Comment by th-otto** [comment]
Could you just apply that patch manually? My PR was messed up, something went wrong when i merged
the current master master branch 2 days ago.

[0001-Fixes-for-make-dist.patch.txt](https://github.com/atari800/atari800/files/3310396/0001-Fixes-for-make-dist.patch.txt)

**Comment by mikrosk** [comment]
Wonderful. Fixed by https://github.com/atari800/atari800/commit/e38eb484e84d0fd9dd2040c9c4c70f9cc41e05e9, thanks!

So now we indeed are ready for release.

**Comment by joysfera** [comment]
Let's see if someone doesn't submit a fix for the #33 in the next few days :-)
