### ISSUE TITLE
DOS package for 4.1.0 missing

### ISSUE THREAD

**Issue by mikesk8** [atari800/atari800#68]
Hi, 
Are you planning to include in the assets DOS version as well? The last one was for 3.1.0 version.

Thanks,
Michal

**Comment by ChoccyHobNob** [comment]
If someone builds a DOS version, it will get included.

**Comment by mikesk8** [comment]
clear :) unfortunately, I don't have skills to do it. 

I was using a DOS version under Mac with Boxer (Dosbox) emulation. It was very easy way to get a Mac version. I will be using 3.1 version then or try Atari800macX (there is a new version too).

**Comment by ChoccyHobNob** [comment]
Go to https://brew.sh <https://brew.sh/> and follow the instructions to install it (if you haven’t already).

Type brew install atari800 Into a terminal window.

When it has finished you will have a working atari800 install, type atari800 into a terminal window to run it.

You can type ln -s /usr/local/bin/atari800 /Users/<youraccount>/Desktop/atari800 Into a terminal to create a link on your desktop which you can double click to run. Put that link wherever you like but be aware it won’t appear in Launchpad if you put it in Applications but you can then drag it to your Dock and launch it from there.

When new versions are released you can just type:

brew update
brew upgrade

To get the latest version

I hope this helps!

**Comment by mikesk8** [comment]
Thank you!
