### ISSUE TITLE
Re Booting Multiboot Disks

### ISSUE THREAD

**Issue by modex100** [atari800/atari800#69]
Hi, 
Have a very weird issues, Atari800 boots normal game disks and execuatable files without flaw. However, back in the day, there was a menudriven boot disk called "Multiboot" enabling many games to be added to a single disk.
These images are sentimental to me as there were my collection from all those years ago.
Unforntually they refuse to boot, yet virtually all other Atari emulators good them without issue.
However, to me this emualtor is by far the best I have seen and would like to use for my multiboot collection.
If you can help with this, I would be eternally grateful.

I have attached an image so that if you get a moment, you can test it and see the result.
I have tried in virtually all congigurations.
For info, this image should boot with 800 OSA OSB and XL, No basic.
[Mboot053.zip](https://github.com/atari800/atari800/files/3389707/Mboot053.zip)

This is a screenshot of what it looks like when loaded

![Multiboot](https://user-images.githubusercontent.com/52881250/61182384-130d8080-a62a-11e9-9ac1-df4a053c2532.jpg)

Many thanks for reading.

Nigel Fletcher

**Comment by ChoccyHobNob** [comment]
Set to PAL, with 1088KB of memory, BASIC off, Stereo On, OS-XL/XE, FastSIO, Hard drive enabled etc. Basically all the things that can stop an ATR from loading enabled and it still works. I tried it with NTSC but all the same settings and it works, turning on BASIC will make it boot but none of the games will run. 
![Mboot053](https://user-images.githubusercontent.com/12753/61184608-793bd880-a615-11e9-986c-b55507383622.gif)

**Comment by mikrosk** [comment]
Closed as not reproducible.
