### ISSUE TITLE
Distribute Atari800 in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [atari800/atari800#71]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by mikrosk** [comment]
This doesn't qualify even as a feature request - missing motivation and use case (what's wrong with current prepackaged builds? atari800 has minimum dependencies)

**Comment by pjmllc** [comment]
Request to reopen this.  Use case is "Run on Steam Deck".

**Comment by mikrosk** [comment]
My reply might have been a bit harsh. However I'm not sure whether there is someone with enough knowledge, resources and willingness to maintain such a package.

So contributions are welcome.

**Comment by pjmllc** [comment]
I got this working.  I was able to load it as a flatpak on my Steam Deck.  What do you thing about posting it to flathub.org?

**Comment by PatrickJMaloney** [comment]
This is pjmllc on my personal account.  I am starting the process to submit this to Flathub.

**Comment by PatrickJMaloney** [comment]
This isn't going to happen.  At least, not by me.  I ran into a reviewer on flathub who was intent on not approving it.  Every time I made a change he requested, he would come up with something else.  When he lied and claimed I refused to do something, that was it.  I'm out.  Later.

**Comment by VR51** [comment]
This is not a flatpack build but if you are interested I wrote a general installer for Linux systems (Debian). If you want to add to it and merge back then I am happy to help. I'm short with time at the mo which is why I'm reaching out to you. Take a look https://github.com/VR51/Atari800-Installer

**Comment by superuser-miguel** [comment]
> This isn't going to happen. At least, not by me. I ran into a reviewer on flathub who was intent on not approving it. Every time I made a change he requested, he would come up with something else. When he lied and claimed I refused to do something, that was it. I'm out. Later.

Do you have a .yaml file I can use to build what you got working?
