### ISSUE TITLE
Question on loading/intro screen for games

### ISSUE THREAD

**Issue by mikesk8** [atari800/atari800#73]
Hello, 
I have a question if its possible to see the loading/intro screen from games? They are loading so fast its not possible to really see them. An example would be International Karate with key mapping screen. 

Thank you,
M.

**Comment by ChoccyHobNob** [comment]
Hit F1
Go to emulator configuration
Set "SIO patch" to No 
Set "Slow booting of DOS binary files" to  Yes

The SIO Patch will slow down ATR file loading to authentic speeds
The Slow booting setting will slow down the speeds XEX files load to about the speed they would load from a floppy disk in a real machine
