### ISSUE TITLE
Improved debugging / monitor

### ISSUE THREAD

**Issue by marcinn** [atari800/atari800#75]
Hi. 

It think that possibility of changing monitor's FILE streams (mon_output, mon_input) will give possibility to communicate with external UI (IDE). Combined with possibility to enter monitor in any time (by sending a command to the socket,stream or something else) and without closing the emulation window, would give a decent development tool.  

What to you think?

**Comment by mikrosk** [comment]
Feel free to create a PR if/when you have something done.
