### ISSUE TITLE
Function keys, caps lock and others ignored from remapped keys

### ISSUE THREAD

**Issue by TauPan** [atari800/atari800#76]
I'd like to use atari800 on a Gemini PDA, a device with a 5 row keyboard that runs both android and linux (debian variant which interfaces to some of the hardware via hybris).

There is no hardware caps-lock key but caps lock is mapped to Fn-Tab. When I press this key, it produces only a tab in the atari emulator and the current value of SHFLOK stays as it is. The workaround here is obviously to press ctrl-c  and then c 2be 0<RET>CONT<RET> in the monitor (or 40 to turn it back on}  which is a bit inconvenient. (I have the same problem in android, but the android version has no monitor, so I need to use the programming environment, e.g. poke.) 

Unfortunately sending F1 or any function key to the emulator from linux appears  impossible.

F1 is mapped to Fn-Shift-1 on the gemini and that key simply arrives as 1.

Then I found this on https://wiki.libsdl.org/CategoryKeyboard:

"A  special exception is the number keys at the top of the keyboard which always map to SDLK_0, SDLK_1, ..., SDLK_9, regardless of layout."

So I thought: Ok, I'll just map Fn-Shift-Q to F1 with xmodmap. Now when I press this combination, any other program sees F1, but not atari800.

No idea how to proceed now, without your help. :)

**Comment by TauPan** [comment]
Forgot to mention, I tried this with current master, built on the device, as well, to no avail.

**Comment by TauPan** [comment]
I just tried on android with hackers keyboard and external keyboard helper and found no way to switch the caps/lower state with a key press. Is this unsupported?

**Comment by TauPan** [comment]
Hmm, maybe #40 would help on android. Apparently the submitter never created a pull request?

**Comment by mikrosk** [comment]
Hmm, seems that way. Can you compile the sources + patch for Android and give it a try?

**Comment by TauPan** [comment]
I can try, but it's been a long while since I compiled anything for android and never with native code. I'll see what I can do.

**Comment by TauPan** [comment]
> I can try, but it's been a long while since I compiled anything for android and never with native code. I'll see what I can do.

Sorry, couldn't make it work. The android instructions are a bit involved and after I was through with them the build failed with some errors that looked like symbols couldn't be found. (Lengthy output, if you want to see it, I can try again.)

Then I thought maybe it would be possible to upgrade to a more recent build environment for android and tried for two evenings to import the project into android studio (see https://developer.android.com/studio/intro/migrate) but in the end somebody who knows how these parts fit together needs to have a look at this. I don't know which source files are needed for what purpose so I'm in way over my head here.

**Comment by mikrosk** [comment]
If you are still around, I can submit @89d's changes and you can test the next release where the changed functionality will be available.

**Comment by mikrosk** [comment]
@TauPan #40 has been merged so if you still care test the next Android release and reopen if necessary.

**Comment by mikrosk** [comment]
Android port is/was maintained by @kr0tki, so when/if he creates the next Android build upon Atari800 release, you will be able to test it.
