### ISSUE TITLE
Instructions for loading tape images required

### ISSUE THREAD

**Issue by jasonculligan** [atari800/atari800#80]
I've read the documentation but sadly cannot figure out how to load a tape image.  I tried escaping to BASIC, typing CLOAD, [ENTER] then F1 to select a CAS image, but nothing happens after that.  Any tips?

**Comment by dmsc** [comment]
Like in a real Atari, to load a binary from tape you must start the computer with the "START" (and normally also "OPTION") keys held, wait for the beep and press any key.

If you give Atari800 the CAS file in the command line, the emulator automatically does that for you, and the tape autoloads.

But if you are loading the tape image via the menu, you must reboot with the full key combo: press and hold F2 (OPTION), F4 (START), then SHIFT and F5 (RESET), and after the beep release all keys and press any key to start loading.
