### ISSUE TITLE
USB joystick support?

### ISSUE THREAD

**Issue by jasonculligan** [atari800/atari800#81]
Are USB joysticks supported?  Asking as I've exhausted documentation and fiddling with menus.

**Comment by joysfera** [comment]
Host joysticks are supported, period. How they are connected to the host we don't care - be it USB, game port, serial, Bluetooth, WiFi - whatever.

BTW, this is not a support forum - we have a mailing list for that.
https://atari800.github.io/contact.html

**Comment by mikrosk** [comment]
Let's hope it is true, otherwise #105 will not be only a platform specific bug as I believe now.

**Comment by joysfera** [comment]
@jasonculligan , your original issue description seems somehow incomplete and my answer little harsh. What is the platform where you have an issue with USB joysticks?
