### ISSUE TITLE
Permission to add Atari 800 emulator core to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [atari800/atari800#87]
Hi there,

we would like to seek your permission to include Atari 800 emulator as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by joysfera** [comment]
I see no issue as long as you respect the GPL.

**Comment by mikrosk** [comment]
I guess we can mark this as solved. ;-)
