### ISSUE TITLE
Is there a way to leave the emulator by program?

### ISSUE THREAD

**Issue by LarsImNetz** [atari800/atari800#91]
I would like to leave the emulator by a simple call like `?usr($600)` from Basic e.g.

Something like
```
dpoke $600,$dea0 :. ldy #$DE (dpoke from Turbobasic)
dpoke $602,$ada2 :. ldx #$AD
poke $604,$f2 :. illegal OPcode CIM
```
The emulator should really exit, not jump into the debugger. 

Or exist there an other way with out press the f9 key?

**Comment by mikrosk** [comment]
Actually, there is a way how to do it, at least I think so (I'm lazy to look for Turbo Basic to verify this): you can compile Atari800 with `--disable-crashmenu`.

However judging from the date of posting I'd say you had found some solution in the meantime. :-)

Feel free to reopen otherwise.
