### ISSUE TITLE
Support for liba8cas

### ISSUE THREAD

**Issue by xtrem007** [atari800/atari800#92]
Is there any chance for add liba8cas support to Atari800 4.2.0 emulator ?
http://a8cas.sourceforge.net/features.html#patch

**Comment by xtrem007** [comment]
Patched atari800 emulator available here:
http://www.arus.net.pl/FUJI/a8cas-util/downloads/modified-atari800-emulator.html

**Comment by mikrosk** [comment]
Actually this shouldn't be dismissed only because someone has made a build. I think it is a good idea to include into Atari800, if there isn't any legal reason not to do so.

**Comment by asiekierka** [comment]
Both projects have matching licenses (GPLv2-or-later).

**Comment by mikrosk** [comment]
If someone can make a proper pull request, that would be nice ;)

**Comment by kr0tki** [comment]
As the author of A8CAS, I would advise against merging it to Atari800 for now. Improvements in emulation accuracy of POKEY timers that I made in A8CAS to support loading of tapes, uncovered inaccuracies in other modules, mainly SIO; the end result is several disk images that have very time-sensitive load routines, stopped loading correctly in Atari800-a8cas. (For example, ATX images of Epyx's "Ballblazer" and "Rescue on Fractalus!") I am unlikely to resolve this problem by myself, as it would require improvements in emulation accuracy to Altirra-like level, a feat not to be done in Atari800 without some significant rewtries of the emulation core.

Other that that, there are other issues, that would be easier to resolve though:
1. As [previously discussed with Petr](https://sourceforge.net/p/atari800/mailman/atari800-users/thread/1267477164.31826.7.camel%40petr/#msg24663579), Dependency on external libraries such as liba8cas is unwelcome unless those libraries are available in Debian. And liba8cas isn't. This could be resolved either by pushing for inclusion of the library in Debian, or by including the liba8cas sources within Atari800 itself.
2. liba8cas is covered by GPL 3.0, so linking Atari800 to it would require to bump its licence from 2.0 to 3.0 as well.

**Comment by mikrosk** [comment]
I don't know what to do here. The patch is now 8 years old and @kr0tki doesn't recommend merging it anyway. Closing as won't fix but of course if anything changes, patches are more than welcome.
