### ISSUE TITLE
Working on SDL2 + WASM support - Progress report

### ISSUE THREAD

**Issue by JeremyJStarcher** [atari800/atari800#98]
I am working on an SDL2 port of the Atari800 emulator, with the goal of having it run fully under WASM.

Some things went remarkably easy, other things took a great deal more work.

The biggest challenge was handling the keyboard.  SDL2 has much better unicode support, but that comes at the cost of a very different input section.  It takes separate routines to handle "input" -- any character that can be typed, vs "keydown" -- meaning, everything else.

So far I have:

- SDL2 window that renders and is resizable.  It scales smoother than the standard SDL window.
- Audio
- Joysticks
- Menu
- NTSC filters
- International keyboards should work, but I have no way to test that.

NOT done or limitations:
- Atari 5200 support.  I know nothing about that.  In some places I left the code in place, but I did not port the keyboard code over.
- Monitor
- WASM support.  (That is coming.)
- hard-coded 32bit colour depth
- Parallel joystick is untested and will likely be removed
- Only tested under Linux Mint
- No code shared between SDL and SDL2, even if it meant copying files or duplicating configuration code blocks. (Not sure if this counts as a plus or as a minus)
- No "extra hardware" tested, including RIO or 80 column devices.  I have no knowledge of them and no way to test.

 
The code still has some jankiness to it that I'd like to clean up, but sneak peeks are welcome.

https://github.com/JeremyJStarcher/atari800

**Comment by joysfera** [comment]
Thanks for the effort. I'd think that sharing as much code between SDL and SDL2 is the better approach as that way you wouldn't run into issues like "parallel joystick is untested".  Wouldn't it be possible to share single file with some ifdefs for the SDL1/SDL2 differences?

**Comment by JeremyJStarcher** [comment]
I could do that if I were to take the original SDL and break it up into chunks.  There are some parts that could be re-used between them, but then that takes me to the issue of I've now made major changes to the SDL1 subsystem that I can't test.

If you'd like me to factor as much common stuff between the two systems I'm more than willing to do that, though.

**Comment by joysfera** [comment]
We gained some experience in a very similar project called ARAnyM (also here on GitHub) where we **YEARS after adding SDL2 support** still distribute binary packages with SDL1 lib. The SDL2 brought its own bugs and most current operating systems (at least desktop ones) are better off with the SDL1 backend.

That means that I would accept a PR **adding**  SDL2 support next to SDL1 to Atari800 immediately because I know the SDL2 is the future, but I also know we will keep distributing SDL1 binaries, so the more common code there is the easier maintenance it will be.

I would be hesitant accepting SDL2 support in their own file(s) as it would probably end up as e.g. DirectX or other unmaintained targets.

**Comment by JeremyJStarcher** [comment]
Do you have a preferred code reformatter?  The default settings under VS code split all the braces onto separate lines.

I am working on what it takes to combine things into one set of common files... trying not to be any more "brutal" than I need to be.

**Comment by joysfera** [comment]
I'll find you the reformatter parameters but I am afraid already since using an editor that starts with reformatting code doesn't sound too friendly with git diff.

**Comment by mikrosk** [comment]
You can always make a separate reformatting commit but it should be definitely only for files which are going to be changed anyway, to avoid polluting history too much.

**Comment by joysfera** [comment]
Nope, there's no reason for committing a code formatting style change just because one has an editor set up wrongly.

**Comment by JeremyJStarcher** [comment]
@joysfera Don't worry, I'll respect the project standards.

On most of my projects I've got a CLI tool that will reformat everything and bring it in line with the project specs... usually tied into `git` so you can't commit badly formatted code

Its made me lazy, that's all.

**Comment by ata-star** [comment]
any news about this?,
sdl1 is not working so well for me

**Comment by JeremyJStarcher** [comment]
It has been a while since I've looked into this but I've looked at it again.

The SDL2 and SDL1 versions are so different that there is simply no way to have them share the same code base between them. The APIs are very, very different.  I played around for a month trying to get them to work and there was simply no reasonable way.

However, the SDL2 changes did allow me to run the code in browser with full sound support.

I understand you being hesitant to bring in a change that will not receive as wide of usage... but looking over other comments in the thread, it is clear there is a desire for an SDL-2/wasm version.

I'd rather not just fork the project -- but at this point the code meets all of my needs.

How would you like to proceed?

**Comment by JeremyJStarcher** [comment]
My git repo is trashed but I do have a running copy of an outdanted branch
on my local machine.

I could share the source but you might need to assemble it.

**Comment by joysfera** [comment]
Last time it failed on your editor that reformatted the source files unnecessarily. Has that been sorted out yet? Patches are still welcome.

**Comment by baktragh** [comment]
An interesting option to get quick and dirty support for SDL2 would be to compile the existing code base against
https://github.com/libsdl-org/sdl12-compat. 

I've tried that under Windows/MSYS and the emulator appears to work decently. The only code change required was to remove forcing specific video drivers in src/sdl/video.c as the video drivers are obviously unknown to SDL2. This can be managed too by forcing the drivers inside #ifndef SDL12_COMPAT_HEADERS ... #endif

**Comment by mikrosk** [comment]
If/when there is something done, feel free to create a PR.
